xmsinterp: /home/conan/xmsinterp/geometry/GmPolygon.cpp File Reference
GmPolygon.cpp File Reference
#include <xmsinterp/geometry/GmPolygon.h>
#include <boost/geometry/geometry.hpp>
#include <xmscore/misc/XmError.h>
#include <xmsinterp/geometry/GmBoostTypes.h>
#include <xmscore/misc/boost_defines.h>
#include <xmsinterp/geometry/GmPolygon.t.h>
#include <boost/assign.hpp>
#include <boost/timer/timer.hpp>
#include <xmscore/testing/TestTools.h>
#include <xmsinterp/geometry/geoms.h>
#include <xmsinterp/geometry/geoms.t.h>
#include <xmscore/misc/carray.h>
Classes
class xms::GmPolygonImpl
Wraps a boost polygon for point in poly, min distance from point to poly etc.
class GmPointInPolyTester_GmPolygon
Helper class for testing GmPolygon.
Functions
static double xms::iDistanceToRing (const GmBstRing3d &a_ring, const Pt3d &a_pt)
Return the minimum distance from the point to a line on the ring.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file GmPolygon.cpp.
Function Documentation
iDistanceToRing()
static double xms::iDistanceToRing (const GmBstRing3d & a_ring, const Pt3d & a_pt) static
Return the minimum distance from the point to a line on the ring.
Parameters
[in] a_ring The ring.
[in] a_pt A point.
Returns
The distance.
Definition at line 75 of file GmPolygon.cpp.
References xms::iDistanceToRing().
Referenced by xms::iDistanceToRing(), and xms::GmPolygonImpl::MinDistanceToBoundary().