xmsinterp: /home/conan/xmsinterp/geometry/GmTriSearch.cpp File Reference
GmTriSearch.cpp File Reference
Provides functionality to do spatial queries on a set of triangles. Uses the boost RTree for queries.
#include <xmsinterp/geometry/GmTriSearch.h>
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/polygon.hpp>
#include <boost/geometry/index/rtree.hpp>
#include <boost/unordered_map.hpp>
#include <boost/iterator/counting_iterator.hpp>
#include <xmscore/math/math.h>
#include <xmscore/stl/utility.h>
#include <xmsinterp/geometry/GmBoostTypes.h>
#include <xmsinterp/geometry/geoms.h>
#include <xmsinterp/geometry/GmPtSearch.h>
#include <xmscore/misc/xmstype.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/misc/XmConst.h>
#include <xmsinterp/geometry/GmTriSearch.t.h>
#include <xmscore/testing/TestTools.h>
#include <xmsinterp/triangulate/TrTin.h>
#include <xmsinterp/triangulate/TrTin.t.h>
Classes
class xms::idx_tri
provides indexing for the spatial index
struct xms::BarycentricVals
Structure for Barycentric coordinate calculations.
class xms::GmTriSearchImpl
Implementation of GmTriSearch.
Macros
#define BARYTOL 1e-6
This is an odd duck tolerance.
Functions
void xms::iCartToBary (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt3, BarycentricVals &a_b)
Converts from Cartesian coordinates to Barycentric coordinates (local triangle coords).
void xms::iGetBarycentricCoords (const Pt3d &a_p, BarycentricVals &a_b, Pt3d &weights)
Calculates weights at the 3 points of a triangle given the location "a_p" and the Barycentric coords of the triangle.
Detailed Description
Provides functionality to do spatial queries on a set of triangles. Uses the boost RTree for queries.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file GmTriSearch.cpp.
Function Documentation
iCartToBary()
void xms::iCartToBary (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt3, BarycentricVals & a_b)
Converts from Cartesian coordinates to Barycentric coordinates (local triangle coords).
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_pt3 Point 3.
a_b Barycentric values.
Definition at line 188 of file GmTriSearch.cpp.
References xms::BarycentricVals::coef, xms::BarycentricVals::dir, xms::gmBaryPrepare(), xms::iCartToBary(), xms::BarycentricVals::orig, xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::GmTriSearchImpl::GetTriBarycentricVals(), and xms::iCartToBary().
iGetBarycentricCoords()
void xms::iGetBarycentricCoords (const Pt3d & a_p, BarycentricVals & a_b, Pt3d & weights)
Calculates weights at the 3 points of a triangle given the location "a_p" and the Barycentric coords of the triangle.
Parameters
a_p A point
a_b Barycentric values.
weights Weights.
Definition at line 203 of file GmTriSearch.cpp.
References xms::BarycentricVals::coef, xms::BarycentricVals::dir, xms::gmCartToBary(), xms::iGetBarycentricCoords(), xms::BarycentricVals::orig, xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::GmTriSearchImpl::FindTriangle(), and xms::iGetBarycentricCoords().