xmsinterp: /home/conan/xmsinterp/interpolate/InterpSignals.cpp File Reference
InterpSignals.cpp File Reference
Signals that can be called when performing idw or kriging interpolation. Used by GMS with Pilot Points.
#include <xmsinterp/interpolate/InterpSignals.h>
Functions
boost::signals2::signal< void(int)> & xms::interp::connectGet::SetDataIndex ()
static file variable
boost::signals2::signal< void(int, double)> & xms::interp::connectGet::FillWtArray ()
static file variable
void xms::inSetDataIndex (int val)
Calls the SetDataIndex signal.
void xms::inFillWtArray (int id, double wt)
calls the FillWtArray signal
Detailed Description
Signals that can be called when performing idw or kriging interpolation. Used by GMS with Pilot Points.
Copyright
(C) Copyright Aquaveo 2018. Distributed under the xmsng Software License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at http://www.aquaveo.com/xmsng/LICENSE_1_0.txt)
Definition in file InterpSignals.cpp.
Function Documentation
inFillWtArray()
void xms::inFillWtArray (int id, double wt)
calls the FillWtArray signal
Parameters
id ID.
wt Weight.
Definition at line 98 of file InterpSignals.cpp.
References xms::inFillWtArray().
Referenced by xms::inFillWtArray().
inSetDataIndex()
void xms::inSetDataIndex (int val)
Calls the SetDataIndex signal.
Parameters
[in] val Value.
Definition at line 89 of file InterpSignals.cpp.
References xms::inSetDataIndex().
Referenced by xms::inSetDataIndex().