xmsinterp: /home/conan/xmsinterp/interpolate/InterpIdw.cpp File Reference
InterpIdw.cpp File Reference
#include <boost/thread.hpp>
#include <xmsinterp/interpolate/InterpIdw.h>
#include <xmscore/math/math.h>
#include <xmscore/stl/utility.h>
#include <xmscore/stl/vector.h>
#include <xmsinterp/geometry/GmPtSearch.h>
#include <xmsinterp/interpolate/InterpSignals.h>
#include <xmsinterp/interpolate/InterpUtil.h>
#include <xmsinterp/interpolate/detail/NodalFunc.h>
#include <xmsinterp/geometry/geoms.h>
#include <xmsinterp/thread/ThreadLoop.h>
#include <xmsinterp/thread/ThreadMgr.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/misc/xmstype.h>
#include <xmsinterp/interpolate/InterpIdw.t.h>
#include <xmscore/testing/TestTools.h>
#include <xmscore/misc/XmLog.h>
Classes
class xms::InterpIdwImpl
Implementation of InterpIdw class.
class xms::InterpIdwImpl::InterpThread
Threading class to compute idw interpolation in parallel.
Functions
static void iGetPoints (std::vector< Pt3d > &a_pts, std::vector< float > &a_scalar, std::vector< Pt3d > &a_iPts)
Get points for testing.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under the xmsng Software License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at http://www.aquaveo.com/xmsng/LICENSE_1_0.txt)
Definition in file InterpIdw.cpp.
Function Documentation
iGetPoints()
static void iGetPoints (std::vector< Pt3d > & a_pts, std::vector< float > & a_scalar, std::vector< Pt3d > & a_iPts) static
Get points for testing.
Parameters
a_pts Points.
a_scalar Scalars.
a_iPts Interpolation points.
Definition at line 699 of file InterpIdw.cpp.
Referenced by InterpIdwUnitTests::testInterp2d_a(), InterpIdwUnitTests::testInterp2d_b(), InterpIdwUnitTests::testInterp2d_c(), InterpIdwUnitTests::testInterp2d_d(), InterpIdwUnitTests::testInterp2d_e(), InterpIdwUnitTests::testInterp2d_f(), and InterpIdwUnitTests::testInterp3d().