xmsinterp: /home/conan/xmsinterp/triangulate/TrTin.t.h File Reference
TrTin.t.h File Reference
#include <boost/shared_ptr.hpp>
#include <cxxtest/TestSuite.h>
Classes
class TrTinUnitTests
Tests for TrTin.
Functions
boost::shared_ptr< xms::TrTin > trBuildTestTin ()
Builds a simple TIN with a hole in the middle.
boost::shared_ptr< xms::TrTin > trBuildTestTin2 ()
Builds a simple TIN for testing.
boost::shared_ptr< xms::TrTin > trBuildTestTin6 ()
Builds a simple TIN for testing.
boost::shared_ptr< xms::TrTin > trBuildTestTin7 ()
Builds a simple TIN for testing.
boost::shared_ptr< xms::TrTin > trBuildTestTin8 ()
Builds a simple TIN with a hole in the middle and a concavity.
boost::shared_ptr< xms::TrTin > trBuildTestTin9 ()
Builds a TIN with long thin triangles for testing.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file TrTin.t.h.
Function Documentation
trBuildTestTin()
boost::shared_ptr<xms::TrTin> trBuildTestTin ()
Builds a simple TIN with a hole in the middle.
///
///  15.0        9
///             /|\
///           /  |  \
///         /  8 | 9  \
///  10.0  6-----7-----8
///        |\  5 |\  6 |\
///        |  \  |  \  |  \
///        | 4  \|    \| 7  \
///   5.0  2-----3-----4-----5
///         \  0 |\  2 | 3  /
///           \  |  \  |  /
///             \| 1  \|/
///   0.0        0-----1
///
///      0.0   5.0   10.0  15.0
///
///
Returns
The tin.
Definition at line 1451 of file TrTin.cpp.
References xms::TrTin::New().
Referenced by TriSearchUnitTests::testTriEnvelopesOverlap().
trBuildTestTin2()
boost::shared_ptr<xms::TrTin> trBuildTestTin2 ()
Builds a simple TIN for testing.
///
///  10.0 6
///       |\
///       |  \
///       |    \
///       |      \
///       |   5    \
///       |          \
///   5.0 4-----------5
///       |\    4    /|\
///       |  \     /  |  \
///       |    \ /    |    \
///       |  2  3  3  |      \
///       |    / \    |        \
///       |  /     \  |    1     \
///       |/    0    \|            \
///   0.0 0-----------1-------------2
///      0.0   2.5   5.0          10.0
///
///
Returns
The tin.
Definition at line 1487 of file TrTin.cpp.
References xms::TrTin::New(), and XM_COUNTOF.
trBuildTestTin6()
boost::shared_ptr<xms::TrTin> trBuildTestTin6 ()
Builds a simple TIN for testing.
///
///  40   36-37--38--39--40--41--42--43--44
///       |\16|\28|\24|\54|51/|52/|\61|\59|
///       |17\|18\|25\|26\|/47|/50|53\|60\|
///  30   27-28--29--30--31--32--33--34--35
///       |\14|\23|\22|\63|48/|49/|\58|\57|
///       |15\|19\|20\|27\|/35|/46|62\|55\|
///  20   18-19--20--21--22--23--24--25--26
///       |\ 3|29/|21/|\30|\32|\45|\41|56/|
///       |1 \|/ 7|/10|13\|33\|34\|42\|/44|
///  10   9--10--11--12--13--14--15--16--17
///       |2 /|\12|8 /|9 /|\37|\36|\38|43/|
///       |/ 0|4 \|/ 5|/ 6|11\|31\|39\|/40|
///   0   0---1---2---3---4---5---6---7---8
///       0  10  20  30  40  50  60  70  80
///
/// (most triangles not shown)
///
Returns
The tin.
Definition at line 1521 of file TrTin.cpp.
References xms::TrTin::New(), and xms::TrTriangulator::Triangulate().
Referenced by TrTinUnitTests::testBoundaries(), TrTinUnitTests::testDeletePoints(), and TrTinUnitTests::testDeleteTriangles().
trBuildTestTin7()
boost::shared_ptr<xms::TrTin> trBuildTestTin7 ()
Builds a simple TIN for testing.
///
//  10-  17-----18------19------20------21
//    |  |\  8  /|\ 11  /|\ 22  / \ 26  /|
//    |  | \   / | \   / | \   /   \   //|
//    |  |  \ /  |  \ /30|23\ / 27  \ / /|
//   5-  |6 13 12|9 14   |  15------16  /|
//    |  |  / \  |  /|\  |  / \ 25  /|28/|
//    |  | /   \ | / | \ | /   \   / | / |
//    |  |/  7  \|/  |  \|/ 24  \ /29| / |
//   0-  9------10 10|3 11------12   | / |
//    |  |\ 13  / \  |  / \ 15  / \  |/  |
//    |  | \   /   \ | /   \   /   \ |/  |
//    |  |  \ /  5  \|/ 16  \ / 21  \|/  |
//  -5-  | 0 5-------6-------7-------8 18|
//    |  |  / \  4  / \ 14  / \ 19  / \  |
//    |  | /   \   /   \   /   \   /   \ |
//    |  |/  1  \ /  2  \ / 20  \ / 17  \|
// -10-  0-------1-------2-------3-------4
//
//       |-------|-------|-------|-------|
//       0      10      20      30      40
///
Returns
The tin.
Definition at line 1565 of file TrTin.cpp.
References xms::TrTin::New(), xms::TrTriangulator::Triangulate(), and XM_COUNTOF.
Referenced by TrOuterTriangleDeleterUnitTests::test1(), and TrBreaklineAdderUnitTests::test2().
trBuildTestTin8()
boost::shared_ptr<xms::TrTin> trBuildTestTin8 ()
Builds a simple TIN with a hole in the middle and a concavity.
///
///  15.0        9----10----11
///             /|\ 10 | 11 /
///           /  |  \  |  /
///         /  8 | 9  \|/
///  10.0  6-----7-----8
///        |\  5 |\  6 |\
///        |  \  |  \  |  \
///        | 4  \|    \| 7  \
///   5.0  2-----3-----4-----5
///         \  0 |\  2 | 3  /
///           \  |  \  |  /
///             \| 1  \|/
///   0.0        0-----1
///
///      0.0   5.0   10.0  15.0
///
///
Returns
The tin.
Definition at line 1599 of file TrTin.cpp.
References xms::TrTin::New().
Referenced by TrBreaklineAdderUnitTests::testCrossingBoundary().
trBuildTestTin9()
boost::shared_ptr<xms::TrTin> trBuildTestTin9 ()
Builds a TIN with long thin triangles for testing.
///
///  10.0 7
///       |\\
///       |  \ \
///       |    \  \
///       |      \  \
///       |   6    \ 7 \
///       |          \   \
///   5.0 4-----------5---6
///       |\    4    /|\   \
///       |  \     /  |  \ 5 \
///       |    \ /    |    \  \
///       |  2  3  3  |      \ \
///       |    / \    |        \ \
///       |  /     \  |    1     \\
///       |/    0    \|            \
///   0.0 0-----------1-------------2
///      0.0   2.5   5.0          10.0
///
///
Returns
The tin.
Definition at line 1635 of file TrTin.cpp.
References xms::TrTin::New(), and XM_COUNTOF.
Referenced by TrTinUnitTests::testRemoveLongThinTrianglesOnPerimeter().