xmsinterp: /home/conan/xmsinterp/triangulate/TrTin.h File Reference
TrTin.h File Reference
#include <iosfwd>
#include <boost/serialization/assume_abstract.hpp>
#include <xmscore/points/ptsfwd.h>
#include <xmscore/misc/base_macros.h>
#include <xmscore/misc/boost_defines.h>
#include <xmscore/stl/vector.h>
#include <xmscore/stl/set.h>
Classes
class xms::TrTin
Functions
void xms::trRenumberOnDelete (const SetInt &a_deleting, VecInt &a_vec)
Boost serialize function.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file TrTin.h.
Function Documentation
trRenumberOnDelete()
void xms::trRenumberOnDelete (const SetInt & a_deleting, VecInt & a_vec)
Boost serialize function.
Renumbers items in a_vec as if deleting items in a_deleting.
Used to renumber m_tris when deleting points. Subtracts 1 from each point index that is greater than or equal to the point index that was deleted. Goes from greatest number being deleted to least so greater numbers get reduced more with each pass.
Parameters
[in] a_deleting Set of numbered things in a_vec being deleted.
[in,out] a_vec Vector of numbered things that gets renumbered.
Definition at line 1376 of file TrTin.cpp.
References xms::trRenumberOnDelete().
Referenced by xms::TrTinImpl::DeletePoints(), and xms::trRenumberOnDelete().