xmsinterp: xms::GmPolyLinePtRedistributerImpl Class Reference
xms::GmPolyLinePtRedistributerImpl Class Reference
Implementation of GmPolyLinePtRedistributer.
Public Member Functions
virtual VecPt3d Redistribute (const VecPt3d &a_input, double a_size) override
Redistributes the distance between points on a polyline based on the a_size value provided to the method.
double PolyLineLengths (const VecPt3d &a_pts, VecDbl &a_lengths)
Calculates the total length (xy) of a polyline as well as the length of each segment.
VecPt3d RedistPolyLineWithNumSeg (const VecPt3d &a_pts, double a_totalLength, const VecDbl &a_lengths, int a_nSeg)
Calculates the total length (xy) of a polyline as well as the length of each segment.
Additional Inherited Members
Static Public Member Functions inherited from xms::GmPolyLinePtRedistributer
static BSHP
< GmPolyLinePtRedistributer > New ()
Creates an instance of this class.
Detailed Description
Implementation of GmPolyLinePtRedistributer.
Definition at line 42 of file GmPolyLinePtRedistributer.cpp.
Member Function Documentation
double xms::GmPolyLinePtRedistributerImpl::PolyLineLengths (const VecPt3d & a_pts, VecDbl & a_lengths)
Calculates the total length (xy) of a polyline as well as the length of each segment.
Parameters
[in] a_pts The point locations of the polyline.
[out] a_lengths The length of each segment of the polyline.
Returns
The length
Definition at line 102 of file GmPolyLinePtRedistributer.cpp.
Referenced by Redistribute().
VecPt3d xms::GmPolyLinePtRedistributerImpl::RedistPolyLineWithNumSeg (const VecPt3d & a_pts, double a_totalLength, const VecDbl & a_lengths, int a_nSeg)
Calculates the total length (xy) of a polyline as well as the length of each segment.
Parameters
[in] a_pts The point locations of the polyline.
[in] a_totalLength The total length of the polyline.
[in] a_lengths The length of each segment of the polyline.
[in] a_nSeg The number of segments for the new polyline.
Returns
The new polyline
Definition at line 123 of file GmPolyLinePtRedistributer.cpp.
Referenced by Redistribute().
VecPt3d xms::GmPolyLinePtRedistributerImpl::Redistribute (const VecPt3d & a_polyLines, double a_size) override virtual
Redistributes the distance between points on a polyline based on the a_size value provided to the method.
Parameters
[in] a_polyLines Point locations defining the polylines.
[in] a_size Target distance between points on the polyline.
Returns
2d vector of redistributed point locations.
Definition at line 85 of file GmPolyLinePtRedistributer.cpp.
References PolyLineLengths(), and RedistPolyLineWithNumSeg().
Referenced by GmPolyLinePtRedistributerUnitTests::testRedistribute(), and GmPolyLinePtRedistributerUnitTests::testRedistribute1().
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/geometry/GmPolyLinePtRedistributer.cpp