xmsinterp: xms::NodalFunc Class Reference
xms::NodalFunc Class Reference
Class to compute gradient plane and quadratic nodal functions for interpolation.
#include <NodalFunc.h>
Public Member Functions
virtual ~NodalFunc ()
Destructor.
Static Public Member Functions
static BSHP< NodalFunc > New (int a_type, bool a_2d, boost::shared_ptr< GmPtSearch > a_ptSearch, const std::vector< Pt3d > &a_pts, const std::vector< float > &a_scalar, int a_nNearest, bool a_quad_oct, double a_power, bool a_modifiedShepardWeights, boost::shared_ptr< Observer > a_p, InterpNatNeigh *a_natNeigh)
Creates a NodalFunc class.
Protected Member Functions
NodalFunc ()
Constructor.
Detailed Description
Class to compute gradient plane and quadratic nodal functions for interpolation.
See Also
NodalFuncImpl
Definition at line 31 of file NodalFunc.h.
Member Function Documentation
BSHP< NodalFunc > xms::NodalFunc::New (int a_type, bool a_2d, boost::shared_ptr< GmPtSearch > a_ptSearch, const std::vector< Pt3d > & a_pts, const std::vector< float > & a_scalar, int a_nNearest, bool a_quad_oct, double a_power, bool a_modifiedShepardWeights, boost::shared_ptr< Observer > a_p, InterpNatNeigh * a_natNeigh) static
Creates a NodalFunc class.
Parameters
[in] a_type The type of nodal function (gradient/quadratic)
[in] a_2d Flag to indicate that only xy and not xyz is considered
[in] a_ptSearch Spatial index for searching points
[in] a_pts The points at which nodal functions are calculated
[in] a_scalar The scalar at the points
[in] a_nNearest The number of nearest points to consider when calculating nodal functions
[in] a_quad_oct Flag to do searching for nearest points based on quadrants (2d) or octants (3d)
[in] a_power Exponent used when calculating weights for nearest points (1/d^a_power)
[in] a_modifiedShepardWeights Flag for calculating weights using the modified shepard's approach
[in] a_p Observer that reports status of interpolation process
[in] a_natNeigh Pointer to a Natural neighbor interpolator. Used if nearest points are found using natural neighbors.
Returns
Shared pointer to an instance of NodalFunc.
Definition at line 169 of file NodalFunc.cpp.
Referenced by xms::InterpIdwImpl::CreateNodalFunctionPtr(), xms::InterpLinearImpl::SetUseCloughTocher(), xms::InterpLinearImpl::SetUseNatNeigh(), and NodalFuncUnitTests::testCreateClass().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/interpolate/detail/NodalFunc.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/interpolate/detail/NodalFunc.cpp