xmsinterp: xms::InterpAnisotropic Class Reference
xms::InterpAnisotropic Class Reference
Class that performs anisotropic interpolation. Transforms points so x is a distance of a projected normal onto the centerline and y is the distance from (above or below) the centerline. Interpolate using inverse distance weighted interpolation after scaling the transformed x-values.
#include <InterpAnisotropic.h>
Public Member Functions
virtual ~InterpAnisotropic ()
Destructor.
Static Public Member Functions
static BSHP< InterpAnisotropic > New ()
Creates an InterpAnisotropic class.
Protected Member Functions
InterpAnisotropic ()
Constructor.
Detailed Description
Class that performs anisotropic interpolation. Transforms points so x is a distance of a projected normal onto the centerline and y is the distance from (above or below) the centerline. Interpolate using inverse distance weighted interpolation after scaling the transformed x-values.
See also
InterpAnisotropicImpl and AnisotropicInterpolator.
InterpAnisotropicImpl
Definition at line 32 of file InterpAnisotropic.h.
Member Function Documentation
New()
BSHP< InterpAnisotropic > xms::InterpAnisotropic::New () static
Creates an InterpAnisotropic class.
Returns
Shared pointer to InterpAnisotropic.
Definition at line 114 of file InterpAnisotropic.cpp.
References xms::InterpAnisotropicImpl::InterpAnisotropicImpl().
Referenced by TutInterpolationIntermediateTests::test_Example_Anisotropic(), and InterpAnisotropicUnitTests::testComplex().
The documentation for this class was generated from the following files:
/home/conan/xmsinterp/interpolate/InterpAnisotropic.h
/home/conan/xmsinterp/interpolate/InterpAnisotropic.cpp