xmsinterp: TutInterpolationIntermediateTests Class Reference
TutInterpolationIntermediateTests Class Reference
Tests for interpolation tutorial.
Public Member Functions
virtual const CxxTest::TestGroup & group ()
Defines the test group.
void test_Example_IDW ()
Example for IDW Interpolation.
void test_Example_Linear ()
[snip_test_Example_Idw]
void test_Example_NaturalNeighbor ()
[snip_test_Example_Linear]
void test_Example_Anisotropic ()
[snip_test_Example_NatNeigh]
Detailed Description
Tests for interpolation tutorial.
Definition at line 22 of file TutInterpolation.t.h.
Member Function Documentation
group()
const CxxTest::TestGroup & TutInterpolationIntermediateTests::group () virtual
Defines the test group.
Returns
CxxTest::TestGroup reference.
Definition at line 63 of file TutInterpolation.cpp.
test_Example_Anisotropic()
void TutInterpolationIntermediateTests::test_Example_Anisotropic ()
[snip_test_Example_NatNeigh]
Example for Anisotropic Interpolation [snip_test_Example_Anisotropic]
Definition at line 169 of file TutInterpolation.cpp.
References xms::InterpAnisotropic::New(), TS_ASSERT_DELTA_VEC, TS_ASSERT_DELTA_VECPT3D, and XM_NODATA.
test_Example_IDW()
void TutInterpolationIntermediateTests::test_Example_IDW ()
Example for IDW Interpolation.
[snip_test_Example_Idw]
Definition at line 73 of file TutInterpolation.cpp.
References xms::InterpIdw::New().
test_Example_Linear()
void TutInterpolationIntermediateTests::test_Example_Linear ()
[snip_test_Example_Idw]
Example for Linear Interpolation [snip_test_Example_Linear]
Definition at line 101 of file TutInterpolation.cpp.
References xms::InterpLinear::New().
test_Example_NaturalNeighbor()
void TutInterpolationIntermediateTests::test_Example_NaturalNeighbor ()
[snip_test_Example_Linear]
Example for Natural Neighbor [snip_test_Example_NatNeigh]
Definition at line 131 of file TutInterpolation.cpp.
References xms::InterpLinear::New().
The documentation for this class was generated from the following files:
/home/conan/xmsinterp/tutorial/TutInterpolation.t.h
/home/conan/xmsinterp/tutorial/TutInterpolation.cpp