xmsinterp: xms::InterpAnisotropicImpl Class Reference
xms::InterpAnisotropicImpl Class Reference
Implementation of InterpAnisotropic class.
Public Member Functions
InterpAnisotropicImpl ()
Constructor.
virtual ~InterpAnisotropicImpl ()
Destructor.
virtual void SetPoints (const VecPt3d &a_centerlinePts, const VecPt3d &a_interpolationPts, bool a_pickClosest=false) override
Set the centerline to define the interpolation space and the points to interpolate from.
virtual float InterpToPt (const Pt3d &a_pt) override
Interpolate z values to a point.
virtual void InterpToPts (const VecPt3d &a_pts, VecFlt &a_result) override
Interpolate z values to many points.
virtual void GetInterpolationPts (VecPt3d &a_interpPoints) override
Get the interpolation points transformed into (s,n,z) space and scaled.
virtual void GetTransformedPts (const VecPt3d &a_points, bool a_pickClosest, VecPt3d &a_transformed) override
Transform points into (s,n,z) space and then scale.
virtual void SetPower (double a_power) override
Set the exponent to use on the inverse distance weighting (defaults to 2).
virtual void SetXScale (double a_xScale) override
Set the scale factor to apply to transformed x (s) coordinates. before computing the inverse distance weighting.
Public Member Functions inherited from xms::InterpAnisotropic
virtual ~InterpAnisotropic ()
Destructor.
Private Attributes
AnisotropicInterpolator m_anisoInterp
An Anisotropic Interpolator.
double m_xScale
double m_power
Additional Inherited Members
Static Public Member Functions inherited from xms::InterpAnisotropic
static BSHP< InterpAnisotropic > New ()
Creates an InterpAnisotropic class.
Protected Member Functions inherited from xms::InterpAnisotropic
InterpAnisotropic ()
Constructor.
Detailed Description
Implementation of InterpAnisotropic class.
Anisotropic interpolation class.
Definition at line 43 of file InterpAnisotropic.cpp.
Constructor & Destructor Documentation
InterpAnisotropicImpl()
xms::InterpAnisotropicImpl::InterpAnisotropicImpl ()
Constructor.
Creates an InterpAnisotropic class.
Definition at line 139 of file InterpAnisotropic.cpp.
Referenced by xms::InterpAnisotropic::New().
Member Function Documentation
GetInterpolationPts()
void xms::InterpAnisotropicImpl::GetInterpolationPts (VecPt3d & a_interpPoints) override virtual
Get the interpolation points transformed into (s,n,z) space and scaled.
Parameters
[out] a_interpPoints The transformed and scaled interpolation points (passed to SetPoints).
Definition at line 192 of file InterpAnisotropic.cpp.
References xms::AnisotropicInterpolator::GetInterpolationPoints(), m_anisoInterp, and m_xScale.
GetTransformedPts()
void xms::InterpAnisotropicImpl::GetTransformedPts (const VecPt3d & a_points, bool a_pickClosest, VecPt3d & a_transformed) override virtual
Transform points into (s,n,z) space and then scale.
Parameters
[in] a_points The points to transform into (s,n,z) space.
[in] a_pickClosest Pick only the transform point closest to the centerline.
[out] a_transformed The points transformed into (s,n,z) space.
[in] a_points The points to transform into (s,n,z) space.
[in] a_pickClosest True to pick only the closest transformed point.
[out] a_transformed The points transformed into (s,n,z) space.
Definition at line 209 of file InterpAnisotropic.cpp.
References m_anisoInterp, m_xScale, and xms::AnisotropicInterpolator::TransformPoint().
InterpToPt()
float xms::InterpAnisotropicImpl::InterpToPt (const Pt3d & a_pt) override virtual
Interpolate z values to a point.
Interpolates to the location specified by a_pt and returns the value.
Parameters
[in] a_pt The point to interpolate to.
Returns
The scaled inverse distance weighted interpolated value.
Parameters
[out] a_pt The location of the interpolation point.
Returns
The interpolated value.
Definition at line 169 of file InterpAnisotropic.cpp.
References xms::AnisotropicInterpolator::GetInterpolationPoints(), xms::AnisotropicInterpolator::InterpolatePoint(), m_anisoInterp, m_power, and m_xScale.
Referenced by InterpToPts().
InterpToPts()
void xms::InterpAnisotropicImpl::InterpToPts (const VecPt3d & a_pts, VecFlt & a_result) override virtual
Interpolate z values to many points.
Interpolates to the locations specified by a_pts and returns the values.
Parameters
[in] a_pts The points to interpolate to.
[out] a_result The interpolated values (one for each of a_pts).
[in] a_pts The points to interpolate to.
[out] a_result The interpolated values.
Definition at line 180 of file InterpAnisotropic.cpp.
References InterpToPt().
SetPoints()
void xms::InterpAnisotropicImpl::SetPoints (const VecPt3d & a_centerlinePts, const VecPt3d & a_interpolationPts, bool a_pickClosest = false) override virtual
Set the centerline to define the interpolation space and the points to interpolate from.
Sets points that will be used for the centerline and interpolation.
Parameters
[in] a_centerlinePts The centerline
[in] a_interpolationPts The points to interpolate from (typically cross sections of the centerline).
[in] a_pickClosest if true, only keep the transformed point for each interpolation point closest to the centerline.
[in] a_centerlinePts Points defining the centerline.
[in] a_interpolationPts Points that will be used to interpolate from.
[in] a_pickClosest If true, only keep one transformed interpolation point (that is closest to the centerline).
Definition at line 158 of file InterpAnisotropic.cpp.
References m_anisoInterp, and xms::AnisotropicInterpolator::SetPoints().
SetPower()
void xms::InterpAnisotropicImpl::SetPower (double a_power) override virtual
Set the exponent to use on the inverse distance weighting (defaults to 2).
Sets the exponent for the interpolation. By default the class does inverse distance squared weighting but the exponent can be changed to any value.
Parameters
[in] a_power The exponent to use.
a_power the exponent used to compute the point weights 1 / distance^a_power
Definition at line 229 of file InterpAnisotropic.cpp.
References m_power.
SetXScale()
void xms::InterpAnisotropicImpl::SetXScale (double a_xScale) override virtual
Set the scale factor to apply to transformed x (s) coordinates. before computing the inverse distance weighting.
Set the.
Parameters
[in] a_xScale The x scale factor to use.
Definition at line 236 of file InterpAnisotropic.cpp.
References m_xScale.
Member Data Documentation
m_power
double xms::InterpAnisotropicImpl::m_power private
The exponent to apply to the inverse distance (default=2.0).
Definition at line 95 of file InterpAnisotropic.cpp.
Referenced by InterpToPt(), and SetPower().
m_xScale
double xms::InterpAnisotropicImpl::m_xScale private
The scale factor to apply to x distance to interpolation points (default=1.0).
Definition at line 93 of file InterpAnisotropic.cpp.
Referenced by GetInterpolationPts(), GetTransformedPts(), InterpToPt(), and SetXScale().
The documentation for this class was generated from the following file:
/home/conan/xmsinterp/interpolate/InterpAnisotropic.cpp