xmsinterp: xms::InterpNatNeighImpl Class Reference
xms::InterpNatNeighImpl Class Reference
Performs natural neighbor interpolation to a location.
Public Member Functions
InterpNatNeighImpl (const std::vector< xms::Pt3d > &a_pts, const std::vector< int > &a_tris, const std::vector< float > &a_scalar, GmTriSearch *a_triSearch)
Consructor.
virtual float InterpToPt (const xms::Pt3d &a_pt) override
Interpolates to a_pt.
virtual void GetNeighbors (int a_ptIdx, std::vector< int > &a_neigh) override
Finds neighboring triangles for the pt at a_ptIdx index in m_pts.
virtual void SetNodalFunc (BSHP< NodalFunc > a_) override
Set the precomputed nodal function.
virtual void RecalcNodalFunc () override
Recalculates the nodal function. This happens when the scalars change.
virtual void SetBlendWeights (bool a_) override
Turns on a flag for using a blending function when calculating weights.
virtual std::string ToString () override
serializes the class to a string
void FillEdgeMap ()
Creates a map of edges for natural neighbor calculations.
void FillCenterVec ()
calculate the circumcircle centers for all triangles
void EdgesFromTri (int a_triIdx, std::pair< int, int > a_edges[3])
fill an array of edges from a triangle index
void NeighTriFromTriIdx (int a_triIdx, std::vector< int > &a_tris)
Gets the adjacent triangles to a_triIdx.
void GetNatNeighTriangles (const xms::Pt3d &a_pt, std::vector< int > &a_tris)
Given a pt this will find the "natural neighbor" triangles. First, we find the triangle that the pt is in. Then we visit the neighbor triangles to see if the point is inside of its circumcircle. If it is then we will also visit the neighbors of that triangle and so on.
double BlendFunc (double a_x)
Blending function to smooth interpolation weights refactored from GMS.
double ScalarFromNodalFunc (int a_ptIdx, const xms::Pt3d &a_loc)
calculates the scalar using the nodal function
double HaleNnInterp (const xms::Pt3d &a_pt)
Implementation of natural neighbor interpolation taken from this paper A stable and fast implementation of natural neighbor interpolation Luming Liang & Dave Hale Center for Wave Phenomena, Colorado School of Mines,Golden, CO 80401, USA April 20, 2010.
void HaleNnVisitNeighbors (int a_tIdx, const xms::Pt3d &a_pt, std::vector< nnOuterEdgeStruct > &a_outerEdges, std::map< int, double > &a_weights)
Visit the neighbors to a_pt and calculate the interpolation weight for the natural neighbors.
int AdjacentTriangle (std::pair< int, int > &a_edge, int a_triIdx)
Gets the triangle adjacent to a_edge.
bool PtInTriCircumCircle (const xms::Pt3d &a_pt, int a_tri)
Determines if a point is inside of a triangle circumcircle.
void HaleNnAddOuterEdge (std::vector< nnOuterEdgeStruct > &a_, int a_tIdx, int a_ptIdx0, int a_ptIdx1, const xms::Pt3d &a_pt)
Adds a nnOuterEdgeStruct to a vector.
void HaleNnSortOuterEdges (std::vector< nnOuterEdgeStruct > &a_)
Sorts the outer edges.
void HaleNnOuterEdgesToWeights (std::vector< nnOuterEdgeStruct > &a_outerEdges, std::map< int, double > &a_weights)
Calculates weights from the outer edges.
void NormalizeWeights (std::map< int, double > &a_weights)
Normalizes the weights so that they sum to 1.0.
void BlendWeights (std::map< int, double > &a_weights)
Blends the weights using BlendFunc. Smooths the interpolation.
double ScalarFromWeights (std::map< int, double > &a_weights, const xms::Pt3d &a_pt)
Computes a scalar at a_pt based on the interpolation weights.
Private Types
typedef boost::unordered_map
< std::pair< int, int >
, std::pair< int, int > > MapEdges
typedef for long template
Private Attributes
const std::vector< xms::Pt3d > & m_pts
points interpolating from
const std::vector< int > & m_tris
triangles interpolating from
const std::vector< float > & m_scalar
scalar interpolating from
double m_tol
tolerance for geometric floating point comparisons
MapEdges m_edges
map of triangle edges
std::vector< xms::Pt3d > m_centers
circumcircle centers of triangles
BSHP< NodalFunc > m_nf
Nodal function (constant, gradient plane, quadratic)
GmTriSearch * m_triSearch
Spatial index for searching triangles.
bool m_blendWeights
flag for blending interpolation weights
Additional Inherited Members
Static Public Member Functions inherited from xms::InterpNatNeigh
static boost::shared_ptr
< InterpNatNeigh > New (const std::vector< Pt3d > &a_pts, const std::vector< int > &a_tris, const std::vector< float > &a_scalar, GmTriSearch *a_triSearch)
Creates a Natural Neighbor Interpolation class.
Protected Member Functions inherited from xms::InterpNatNeigh
InterpNatNeigh ()
Constructor.
virtual ~InterpNatNeigh ()
Destructor.
Detailed Description
Performs natural neighbor interpolation to a location.
Definition at line 59 of file InterpNatNeigh.cpp.
Constructor & Destructor Documentation
xms::InterpNatNeighImpl::InterpNatNeighImpl (const std::vector< xms::Pt3d > & a_pts, const std::vector< int > & a_tris, const std::vector< float > & a_scalar, GmTriSearch * a_triSearch)
Consructor.
Parameters
[in] a_pts Locations that are interpolated from
[in] a_tris Triangles connecting a_pts and defining neighbors
[in] a_scalar Scalars that are interpolated from
[in] a_triSearch Spatial index for searching triangles
Definition at line 169 of file InterpNatNeigh.cpp.
References FillCenterVec(), and FillEdgeMap().
Member Function Documentation
int xms::InterpNatNeighImpl::AdjacentTriangle (std::pair< int, int > & a_edge, int a_triIdx)
Gets the triangle adjacent to a_edge.
Parameters
[in] a_edge A triangle edge
[in] a_triIdx Triangle index
Returns
the index to the adjacent triangle. If there is no adjacent triangle then the return value is XM_NONE.
Definition at line 509 of file InterpNatNeigh.cpp.
References m_edges, and XM_NONE.
Referenced by HaleNnVisitNeighbors().
double xms::InterpNatNeighImpl::BlendFunc (double x)
Blending function to smooth interpolation weights refactored from GMS.
Parameters
x interpolation weight
Returns
The blended value.
Definition at line 400 of file InterpNatNeigh.cpp.
Referenced by BlendWeights().
void xms::InterpNatNeighImpl::BlendWeights (std::map< int, double > & a_weights)
Blends the weights using BlendFunc. Smooths the interpolation.
Parameters
[out] a_weights The interpolation weights
Definition at line 623 of file InterpNatNeigh.cpp.
References BlendFunc().
Referenced by HaleNnInterp().
void xms::InterpNatNeighImpl::EdgesFromTri (int a_triIdx, std::pair< int, int > a_edges[3])
fill an array of edges from a triangle index
Parameters
[in] a_triIdx Index of the triangle
[out] a_edges Array of triangle edges filled by this method
Definition at line 326 of file InterpNatNeigh.cpp.
References m_tris.
Referenced by FillEdgeMap(), and NeighTriFromTriIdx().
void xms::InterpNatNeighImpl::GetNatNeighTriangles (const xms::Pt3d & a_pt, std::vector< int > & a_tris)
Given a pt this will find the "natural neighbor" triangles. First, we find the triangle that the pt is in. Then we visit the neighbor triangles to see if the point is inside of its circumcircle. If it is then we will also visit the neighbors of that triangle and so on.
Parameters
[in] a_pt The location to find the natural neighbor triangles
[out] a_tris The triangle indexes that are natural neighbors to a_pt
Definition at line 361 of file InterpNatNeigh.cpp.
References m_centers, m_tris, m_triSearch, NeighTriFromTriIdx(), and XM_NONE.
Referenced by GetNeighbors(), and InterpNatNeighUnitTests::testGetTris().
void xms::InterpNatNeighImpl::GetNeighbors (int a_ptIdx, std::vector< int > & a_neigh) override virtual
Finds neighboring triangles for the pt at a_ptIdx index in m_pts.
Parameters
[in] a_ptIdx Index to the point where we want to find its neighbor triangles
[out] a_neigh Vector of triangle indexes
Definition at line 200 of file InterpNatNeigh.cpp.
References GetNatNeighTriangles(), m_pts, and m_tris.
Referenced by InterpNatNeighUnitTests::testGetNeighbors().
void xms::InterpNatNeighImpl::HaleNnAddOuterEdge (std::vector< nnOuterEdgeStruct > & a_, int a_tIdx, int a_ptIdx0, int a_ptIdx1, const xms::Pt3d & a_pt)
Adds a nnOuterEdgeStruct to a vector.
Parameters
[out] a_ Vector of outer edges
[in] a_tIdx Triangle index
[in] a_ptIdx0 Point index for first point on edge of triangle a_tIdx
[in] a_ptIdx1 Point index for second point on edge of triangle a_tIdx
[in] a_pt Location used to find this outer edge
Definition at line 543 of file InterpNatNeigh.cpp.
References xms::nnOuterEdgeStruct::m_cc, xms::nnOuterEdgeStruct::m_edge, m_pts, m_tol, and xms::nnOuterEdgeStruct::m_triIdx.
Referenced by HaleNnVisitNeighbors().
double xms::InterpNatNeighImpl::HaleNnInterp (const xms::Pt3d & a_pt)
Implementation of natural neighbor interpolation taken from this paper A stable and fast implementation of natural neighbor interpolation Luming Liang & Dave Hale Center for Wave Phenomena, Colorado School of Mines,Golden, CO 80401, USA April 20, 2010.
Parameters
[in] a_pt The location being interpolated to
Returns
The interpolated value at a_pt
Definition at line 428 of file InterpNatNeigh.cpp.
References BlendWeights(), HaleNnOuterEdgesToWeights(), HaleNnSortOuterEdges(), HaleNnVisitNeighbors(), m_blendWeights, m_triSearch, NormalizeWeights(), ScalarFromWeights(), and XM_NONE.
Referenced by InterpToPt(), and InterpNatNeighUnitTests::testHaleNnInterp().
void xms::InterpNatNeighImpl::HaleNnOuterEdgesToWeights (std::vector< nnOuterEdgeStruct > & a_outerEdges, std::map< int, double > & a_weights)
Calculates weights from the outer edges.
Parameters
[in] a_outerEdges The outer edges
[out] a_weights Weight calculated for each outer edge
Definition at line 578 of file InterpNatNeigh.cpp.
References xms::nnOuterEdgeStruct::m_cc, m_centers, xms::nnOuterEdgeStruct::m_edge, and xms::nnOuterEdgeStruct::m_triIdx.
Referenced by HaleNnInterp().
void xms::InterpNatNeighImpl::HaleNnSortOuterEdges (std::vector< nnOuterEdgeStruct > & a_)
Sorts the outer edges.
Parameters
[out] a_ Vector of outer edges
Definition at line 561 of file InterpNatNeigh.cpp.
Referenced by HaleNnInterp(), and InterpNatNeighUnitTests::testHaleNnSortOuterEdges().
void xms::InterpNatNeighImpl::HaleNnVisitNeighbors (int a_tIdx, const xms::Pt3d & a_pt, std::vector< nnOuterEdgeStruct > & a_outerEdges, std::map< int, double > & a_weights)
Visit the neighbors to a_pt and calculate the interpolation weight for the natural neighbors.
Parameters
[in] a_tIdx Starting triangle index
[in] a_pt Location used to find natural neighbors
[out] a_outerEdges Outer edges for a_pt
[out] a_weights Interpolation weight for neighbor triangle
Definition at line 460 of file InterpNatNeigh.cpp.
References AdjacentTriangle(), HaleNnAddOuterEdge(), m_centers, m_tris, PtInTriCircumCircle(), and XM_NONE.
Referenced by HaleNnInterp().
float xms::InterpNatNeighImpl::InterpToPt (const xms::Pt3d & a_pt) override virtual
Interpolates to a_pt.
Parameters
[in] a_pt The location to interpolate to
Returns
The interpolated value at a_pt
Definition at line 190 of file InterpNatNeigh.cpp.
References HaleNnInterp().
void xms::InterpNatNeighImpl::NeighTriFromTriIdx (int a_triIdx, std::vector< int > & a_tris)
Gets the adjacent triangles to a_triIdx.
Parameters
[in] a_triIdx Index of the triangle
[out] a_tris Indexes of adjacent triangles
Definition at line 337 of file InterpNatNeigh.cpp.
References EdgesFromTri(), m_edges, and XM_NONE.
Referenced by GetNatNeighTriangles().
void xms::InterpNatNeighImpl::NormalizeWeights (std::map< int, double > & a_weights)
Normalizes the weights so that they sum to 1.0.
Parameters
[out] a_weights The interpolation weights
Definition at line 610 of file InterpNatNeigh.cpp.
Referenced by HaleNnInterp().
bool xms::InterpNatNeighImpl::PtInTriCircumCircle (const xms::Pt3d & a_pt, int a_tri)
Determines if a point is inside of a triangle circumcircle.
Parameters
[in] a_pt The location to test
[in] a_tri Index to the triangle
Returns
true if the point is inside the circumcircle
Definition at line 527 of file InterpNatNeigh.cpp.
References m_centers.
Referenced by HaleNnVisitNeighbors().
double xms::InterpNatNeighImpl::ScalarFromNodalFunc (int a_ptIdx, const xms::Pt3d & a_loc)
calculates the scalar using the nodal function
Parameters
[in] a_ptIdx Index to point in m_pts
[in] a_loc Location being interpolated to
Returns
the scalar adjusted by the nodal function
Definition at line 410 of file InterpNatNeigh.cpp.
References m_nf, and m_scalar.
Referenced by ScalarFromWeights().
double xms::InterpNatNeighImpl::ScalarFromWeights (std::map< int, double > & a_weights, const xms::Pt3d & a_pt)
Computes a scalar at a_pt based on the interpolation weights.
Parameters
[in] a_weights The interpolation weights
[in] a_pt The location interpolated to.
Returns
The interpolated value at a_pt.
Definition at line 641 of file InterpNatNeigh.cpp.
References ScalarFromNodalFunc().
Referenced by HaleNnInterp().
void xms::InterpNatNeighImpl::SetBlendWeights (bool a_) override virtual
Turns on a flag for using a blending function when calculating weights.
Parameters
[in] a_ flag to turn on weight blending
Definition at line 237 of file InterpNatNeigh.cpp.
References m_blendWeights.
void xms::InterpNatNeighImpl::SetNodalFunc (BSHP< NodalFunc > a_) override virtual
Set the precomputed nodal function.
Parameters
a_ The nodal function class.
Definition at line 221 of file InterpNatNeigh.cpp.
References m_nf.
std::string xms::InterpNatNeighImpl::ToString () override virtual
serializes the class to a string
Returns
The string.
Definition at line 245 of file InterpNatNeigh.cpp.
References m_blendWeights, m_centers, m_edges, m_pts, m_scalar, m_tol, and m_tris.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/interpolate/detail/InterpNatNeigh.cpp