xmsinterp: xms::TrTin Class Reference
xms::TrTin Class Reference
Public Member Functions
virtual ~TrTin ()
destructor
Static Public Member Functions
static BSHP< TrTin > New ()
Create a TrTinImpl object.
Protected Member Functions
TrTin ()
constructor
Detailed Description
See Also
TrTinImpl
Definition at line 35 of file TrTin.h.
Member Function Documentation
BSHP< TrTin > xms::TrTin::New () static
Create a TrTinImpl object.
Returns
TrTin.
Definition at line 1242 of file TrTin.cpp.
Referenced by TrAutoFixFourTrianglePtsUnitTests::test1(), TrBreaklineAdderUnitTests::test1(), TrTinUnitTests::test1(), TrTinUnitTests::testOptimizeTriangulation(), TrTinUnitTests::testSwap(), trBuildTestTin(), trBuildTestTin2(), trBuildTestTin6(), trBuildTestTin7(), and trBuildTestTin8().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/triangulate/TrTin.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/triangulate/TrTin.cpp