xmsinterp: xms::TrBreaklineAdderImpl Class Reference
xms::TrBreaklineAdderImpl Class Reference
Adds breaklines to a triangulation.
Public Member Functions
virtual void SetObserver (BSHP< Observer > a_) override
Set the observer to use for feedback while processing.
virtual void SetTin (BSHP< TrTin > a_tin, double a_tol=-1) override
Sets the tin that will have breaklines added to it.
virtual void AddBreakline (const VecInt &a_breakline) override
Add a breakline by swapping. Compare to bkProcessScatBySwapping.
virtual void AddBreaklines (const VecInt2d &a_breakline) override
Add breaklines by swapping. Compare to bkProcessScatBySwapping.
virtual std::string ErrorMessage (int) const override
Returns the error message associated with the given number.
Private Member Functions
bool GetExtents ()
Computes the extents (min, max) of the polygon.
void ComputeTolerance ()
Computes a tolerance to use based on point extents.
bool CrossesBoundary (int a_blpt1, int a_blpt2)
Returns true if the line connecting the two points crosses the tin boundary.
void ProcessSegmentBySwapping (int a_vtx1, int a_vtx2)
Insert breakline segment into triangulation by swapping triangle edges. Compare to bkiProcessScatSegmentBySwapping.
void GetIntersectingEdges (int a_blpt1, int a_blpt2, VecEdge &a_edges)
Find triangle edges which intersect the breakline. Compare to bkiGetListOfIntersectingScatEdges.
void FindIntersectingEdgeFromPoint (int a_blpt1, int a_blpt2, int *a_intpt1, int *a_intpt2, double *a_x, double *a_y, double *a_z1, double *a_z2)
Finds edge opposite of a_blpt1 intersected by breakline segment a_blpt1, a_blpt2. Compare to bkiFindIntersectingEdgeFromVertex.
void FindIntersectingEdgeFromEdge (int a_ept1, int a_ept2, int a_blpt1, int a_blpt2, int *a_intpt1, int *a_intpt2, double *a_x, double *a_y, double *a_z1, double *a_z2)
Finds edge of triangle intersected by breakline and returns next edge in a_intpt1 and a_intpt2. Compare to bkiFindIntersectingScatEdgeFromEdge.
Private Attributes
BSHP< TrTin > m_tin
The tin.
BSHP< Observer > m_observer
The observer.
double m_xyTol
Xy tolerance used with geom functions.
size_t m_totNumSegs
Total num segments. For progress.
size_t m_segCount
Current segment. For progress.
VecInt * m_tris
Pointer to m_tin triangles for convenience.
VecPt3d * m_pts
Pointer to m_tin points for convenience.
VecInt2d * m_trisAdjToPts
Pointer to m_tin trisAdjToPts for convenience.
Pt3d m_mn
Minimum extent of all points.
Pt3d m_mx
Maximum extent of all points.
BSHP< GmMultiPolyIntersector > m_multiPolyIntersector
Used to check if breakline crosses boundary.
BSHP< GmPtSearch > m_searcher
Used to check if breakline crosses boundary.
Additional Inherited Members
Static Public Member Functions inherited from xms::TrBreaklineAdder
static boost::shared_ptr
< TrBreaklineAdder > New ()
Create a TrBreaklineAdderImpl object.
Detailed Description
Adds breaklines to a triangulation.
Definition at line 60 of file TrBreaklineAdder.cpp.
Member Function Documentation
void xms::TrBreaklineAdderImpl::AddBreakline (const VecInt & a_breakline) override virtual
Add a breakline by swapping. Compare to bkProcessScatBySwapping.
Currently does not consider points that are coincident with the breakline.
Parameters
a_breakline The breakline to add as indices of m_tin->Points().
Definition at line 181 of file TrBreaklineAdder.cpp.
References m_observer, m_segCount, m_tin, m_totNumSegs, ProcessSegmentBySwapping(), and XM_ENSURE_TRUE_T_NO_ASSERT.
Referenced by AddBreaklines().
void xms::TrBreaklineAdderImpl::AddBreaklines (const VecInt2d & a_breaklines) override virtual
Add breaklines by swapping. Compare to bkProcessScatBySwapping.
Currently does not consider points that are coincident with the breakline.
Parameters
a_breaklines The breaklines to add as indices of m_tin->Points().
Definition at line 224 of file TrBreaklineAdder.cpp.
References AddBreakline(), m_observer, m_segCount, m_tin, m_totNumSegs, and XM_ENSURE_TRUE_T_NO_ASSERT.
bool xms::TrBreaklineAdderImpl::CrossesBoundary (int a_blpt1, int a_blpt2) private
Returns true if the line connecting the two points crosses the tin boundary.
Parameters
a_blpt1 First point of breakline segment.
a_blpt2 Second point of breakline segment.
Returns
true if the line connecting the two points crosses a boundary.
Definition at line 278 of file TrBreaklineAdder.cpp.
References m_multiPolyIntersector, m_searcher, m_tin, m_xyTol, xms::GmPtSearch::New(), and xms::GmMultiPolyIntersector::New().
Referenced by ProcessSegmentBySwapping().
std::string xms::TrBreaklineAdderImpl::ErrorMessage (int a_messageNumber) const override virtual
Returns the error message associated with the given number.
Parameters
[in] a_messageNumber Number associated with an error message.
Returns
The error message.
Definition at line 257 of file TrBreaklineAdder.cpp.
References XM_ASSERT.
void xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromEdge (int a_ept1, int a_ept2, int a_blpt1, int a_blpt2, int * a_intpt1, int * a_intpt2, double * a_x, double * a_y, double * a_z1, double * a_z2) private
Finds edge of triangle intersected by breakline and returns next edge in a_intpt1 and a_intpt2. Compare to bkiFindIntersectingScatEdgeFromEdge.
Parameters
a_ept1 First point of starting edge.
a_ept2 Second point of starting edge.
a_blpt1 First point of breakline segment.
a_blpt2 Second point of breakline segment.
a_intpt1 First point of intersecting edge, or -1 if not found.
a_intpt2 Second point of intersecting edge, or -1 if not found.
a_x x value of intersection.
a_y y value of intersection.
a_z1 z value of intersection.
a_z2 z value of intersection.
Definition at line 503 of file TrBreaklineAdder.cpp.
References m_pts, m_tin, m_xyTol, and XM_ENSURE_TRUE_T_NO_ASSERT.
Referenced by GetIntersectingEdges().
void xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromPoint (int a_blpt1, int a_blpt2, int * a_intpt1, int * a_intpt2, double * a_x, double * a_y, double * a_z1, double * a_z2) private
Finds edge opposite of a_blpt1 intersected by breakline segment a_blpt1, a_blpt2. Compare to bkiFindIntersectingEdgeFromVertex.
Parameters
a_blpt1 First breakline segment point.
a_blpt2 Second breakline segment point.
a_intpt1 First point on intersecting edge, or -1 if not found.
a_intpt2 Second point on intersecting edge, or -1 if not found.
a_x x value of intersection.
a_y y value of intersection.
a_z1 z value of intersection.
a_z2 z value of intersection.
Definition at line 457 of file TrBreaklineAdder.cpp.
References m_pts, m_tin, and m_xyTol.
Referenced by GetIntersectingEdges().
bool xms::TrBreaklineAdderImpl::GetExtents () private
Computes the extents (min, max) of the polygon.
Returns
true if there are any points and the extents were computed.
Definition at line 554 of file TrBreaklineAdder.cpp.
References m_mn, m_mx, and m_tin.
Referenced by ComputeTolerance().
void xms::TrBreaklineAdderImpl::GetIntersectingEdges (int a_blpt1, int a_blpt2, VecEdge & a_edges) private
Find triangle edges which intersect the breakline. Compare to bkiGetListOfIntersectingScatEdges.
Parameters
a_blpt1 First point of breakline segment.
a_blpt2 Second point of breakline segment.
a_edges Edges which intersect the breakline.
Definition at line 410 of file TrBreaklineAdder.cpp.
References FindIntersectingEdgeFromEdge(), FindIntersectingEdgeFromPoint(), xms::edgerecord::intersection, xms::edgerecord::pt1, xms::edgerecord::pt2, xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by ProcessSegmentBySwapping().
void xms::TrBreaklineAdderImpl::ProcessSegmentBySwapping (int a_blpt1, int a_blpt2) private
Insert breakline segment into triangulation by swapping triangle edges. Compare to bkiProcessScatSegmentBySwapping.
Parameters
a_blpt1 First point of breakline segment.
a_blpt2 Second point of breakline segment.
Definition at line 325 of file TrBreaklineAdder.cpp.
References CrossesBoundary(), GetIntersectingEdges(), m_pts, m_tin, m_xyTol, xmlog::warning, and XM_LOG.
Referenced by AddBreakline().
virtual void xms::TrBreaklineAdderImpl::SetObserver (BSHP< Observer > a_) inline override virtual
Set the observer to use for feedback while processing.
Parameters
a_ The observer.
Definition at line 68 of file TrBreaklineAdder.cpp.
References m_observer.
void xms::TrBreaklineAdderImpl::SetTin (BSHP< TrTin > a_tin, double a_tol = -1) override virtual
Sets the tin that will have breaklines added to it.
Parameters
a_tin The tin to be modified.
a_tol Tolerance used when intersecting line segments. Optional. If not specified, one is computed from the tin extents.
Definition at line 152 of file TrBreaklineAdder.cpp.
References ComputeTolerance(), m_pts, m_tin, m_tris, m_trisAdjToPts, m_xyTol, and XM_ENSURE_TRUE_T_NO_ASSERT.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/triangulate/TrBreaklineAdder.cpp