xmsinterp: AnisotropicInterpolatorUnitTests Class Reference
AnisotropicInterpolatorUnitTests Class Reference
Unit tests for the AnisotropicInterpolator class.
Public Member Functions
void testSimple ()
Tests simple interpolation problem.
void testCrossSectionThroughPoint ()
Tests interpolation of crosssection going through a centerline point.
void testAmbiguity ()
Test to demonstrate ambiguity.
Detailed Description
Unit tests for the AnisotropicInterpolator class.
Definition at line 28 of file AnisotropicInterpolator.t.h.
Member Function Documentation
testAmbiguity()
void AnisotropicInterpolatorUnitTests::testAmbiguity ()
Test to demonstrate ambiguity.
///  +                     +
///   \       +   +       /
///    \     /     \     /
///     \   /       \   /
///      \ /    *    \ /
///       X           X
///      / \         / \
///     /   \       /   \
///    /     \     /     \
///   +       \   /       +
///            \ /
///             +
///
///             *
///
Definition at line 578 of file AnisotropicInterpolator.cpp.
References xms::AnisotropicInterpolator::GetInterpolationPoints(), xms::AnisotropicInterpolator::InterpolatePoint(), xms::AnisotropicInterpolator::SetPoints(), xms::AnisotropicInterpolator::TransformPoint(), and TS_ASSERT_DELTA_VECPT3D.
testCrossSectionThroughPoint()
void AnisotropicInterpolatorUnitTests::testCrossSectionThroughPoint ()
Tests interpolation of crosssection going through a centerline point.
/// +                         +
///  \                       /
///   \                     /
///    +-------------------+
///    |\                 /|
///    | \               / |
///    |  \             /  |
///    |   +           +   |
///    +                   +
///
Definition at line 523 of file AnisotropicInterpolator.cpp.
References xms::AnisotropicInterpolator::CrossProduct(), xms::AnisotropicInterpolator::GetInterpolationPoints(), xms::AnisotropicInterpolator::InterpolatePoint(), xms::AnisotropicInterpolator::SetPoints(), xms::AnisotropicInterpolator::TransformPoint(), TS_ASSERT_DELTA_VECPT3D, and xms::Pt3< T >::z.
The documentation for this class was generated from the following files:
/home/conan/xmsinterp/interpolate/detail/AnisotropicInterpolator.t.h
/home/conan/xmsinterp/interpolate/detail/AnisotropicInterpolator.cpp