xmsinterp: xms::GmTriSearchImpl Class Reference
xms::GmTriSearchImpl Class Reference
Implementation of GmTriSearch.
Public Member Functions
GmTriSearchImpl ()
Constructor.
virtual ~GmTriSearchImpl ()
Destructor.
virtual void TrisToSearch (BSHP< std::vector< Pt3d >> a_pts, BSHP< std::vector< int >> a_tris) override
Adds the triangles to the class.
virtual void SetPtActivity (DynBitset &a_activity) override
Modifies the activity bitset of the points.
virtual void SetTriActivity (DynBitset &a_activity) override
Modifies the activity bitset of the triangles.
virtual DynBitset GetPtActivity () override
Activity of the points based on the triangle activity.
bool ActiveTri (int a_idx)
Tests if a triangle is active. If any of the points of the tri are not active then the tri is not active.
virtual int TriContainingPt (const Pt3d &a_pt) override
Find the triangle containing the point.
virtual void TriEnvelopsContainingPt (const Pt3d &a_pt, std::vector< int > &a_tris) override
Find all triangles whose envelope contains the point.
virtual void TriEnvelopesOverlap (const Pt3d &a_pMin, const Pt3d &a_pMax, std::vector< int > &a_tris) override
Find all triangles whose envelope overlaps the envelope defined by a_pMin and a_pMax.
virtual bool InterpWeights (const Pt3d &a_pt, std::vector< int > &a_idxs, std::vector< double > &a_wts) override
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
virtual bool InterpWeightsTriangleIdx (const Pt3d &a_pt, int &a_triangleIdx, std::vector< int > &a_idxs, std::vector< double > &a_wts) override
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
virtual std::string ToString () const override
Write the internals to a string.
void CreateRTree ()
Creates the RTree of the triangles.
void PointIdxesFromTriIdx (int a_triIdx, int a_ptIdxes[3])
Fills in the point indices based on the triangle index.
int FindTriangle (const Pt3d &a_pt, int ix[3], Pt3d &weights)
Find the triangle containing the location a_pt.
void GetTriBarycentricVals (int a_idx, int a_ix[3], BarycentricVals &a_b)
Gets the barycentric values for a triangle.
DynBitset PointActivityFromTriActivity ()
Gets the activity of the points from the triangles.
BSHP< GmPtSearch > CreatePtSearch ()
creates the rtree of the points
Public Member Functions inherited from xms::GmTriSearch
virtual ~GmTriSearch ()
Destructor.
Public Attributes
Pt3d m_min
mininum extents of all points
Pt3d m_max
maximum extents of all points
BSHP< std::vector< Pt3d > > m_pts
point locations
BSHP< std::vector< int > > m_tris
triangles that reference point indexes
DynBitset m_triActivity
activity of the triangles
boost::unordered_map< size_t, BarycentricVals > m_cache
bgi::rtree< value, qRtree, idx_tri > * m_rTree
spatial index of the triangle extents
Additional Inherited Members
Static Public Member Functions inherited from xms::GmTriSearch
static BSHP< GmTriSearch > New ()
Creates an TriSearch class.
Protected Member Functions inherited from xms::GmTriSearch
GmTriSearch ()
Constructor.
Detailed Description
Implementation of GmTriSearch.
Provides functionality to do spatial queries on a set of triangles. Uses the boost RTree for queries.
Definition at line 125 of file GmTriSearch.cpp.
Member Function Documentation
ActiveTri()
bool xms::GmTriSearchImpl::ActiveTri (int a_idx)
Tests if a triangle is active. If any of the points of the tri are not active then the tri is not active.
Parameters
a_idx Triangle index
Returns
true if the triangle a_idx is active.
Definition at line 361 of file GmTriSearch.cpp.
References m_triActivity.
Referenced by FindTriangle(), and PointActivityFromTriActivity().
CreatePtSearch()
BSHP< GmPtSearch > xms::GmTriSearchImpl::CreatePtSearch ()
creates the rtree of the points
Returns
GmPtSearch.
Definition at line 622 of file GmTriSearch.cpp.
References m_pts, xms::GmPtSearch::New(), and PointActivityFromTriActivity().
FindTriangle()
int xms::GmTriSearchImpl::FindTriangle (const Pt3d & a_pt, int ix[3], Pt3d & weights)
Find the triangle containing the location a_pt.
Parameters
a_pt The location to interpolate to.
ix The point indices from the triangle containing a_pt.
weights The weights associated with the points ix.
Returns
index to the triangle containg a_pt.
Definition at line 515 of file GmTriSearch.cpp.
References ActiveTri(), BARYTOL, xmlog::error, GetTriBarycentricVals(), xms::iGetBarycentricCoords(), m_pts, m_rTree, m_tris, xms::Pt3< T >::x, XM_LOG, XM_NONE, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by InterpWeightsTriangleIdx(), and TriContainingPt().
GetPtActivity()
virtual DynBitset xms::GmTriSearchImpl::GetPtActivity () inline override virtual
Activity of the points based on the triangle activity.
Returns
boost::dynamic_bitset of size_t
Definition at line 135 of file GmTriSearch.cpp.
GetTriBarycentricVals()
void xms::GmTriSearchImpl::GetTriBarycentricVals (int a_idx, int a_ix[3], BarycentricVals & a_b)
Gets the barycentric values for a triangle.
Parameters
a_idx Triangle index
a_ix Point indexes that make up triangle
a_b The barycentric values
Definition at line 582 of file GmTriSearch.cpp.
References xms::iCartToBary(), m_cache, and m_pts.
Referenced by FindTriangle().
InterpWeights()
bool xms::GmTriSearchImpl::InterpWeights (const Pt3d & a_pt, std::vector< int > & a_idxs, std::vector< double > & a_wts) override virtual
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
Parameters
a_pt Location that is interpolated to.
a_idxs Vector of triangle point indices filled in by this method.
a_wts Vector of triangle point weights filled in by this method.
Returns
false if a_pt is not inside of any triangle
Definition at line 433 of file GmTriSearch.cpp.
References InterpWeightsTriangleIdx().
InterpWeightsTriangleIdx()
bool xms::GmTriSearchImpl::InterpWeightsTriangleIdx (const Pt3d & a_pt, int & a_triangleIdx, std::vector< int > & a_idxs, std::vector< double > & a_wts) override virtual
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
Parameters
a_pt Location that is interpolated to.
a_triangleIdx Found triangles index in triangle array (zero based count*3).
a_idxs Vector of triangle point indices filled in by this method.
a_wts Vector of triangle point weights filled in by this method.
Returns
false if a_pt is not inside of any triangle
Definition at line 449 of file GmTriSearch.cpp.
References FindTriangle(), xms::Pt3< T >::x, XM_NONE, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by InterpWeights().
PointActivityFromTriActivity()
DynBitset xms::GmTriSearchImpl::PointActivityFromTriActivity ()
Gets the activity of the points from the triangles.
Returns
bitset of the activity of the points.
Definition at line 598 of file GmTriSearch.cpp.
References ActiveTri(), m_pts, m_triActivity, and m_tris.
Referenced by CreatePtSearch().
PointIdxesFromTriIdx()
void xms::GmTriSearchImpl::PointIdxesFromTriIdx (int a_triIdx, int a_ptIdxes[3])
Fills in the point indices based on the triangle index.
Parameters
a_triIdx The triangle index in the m_tris vector.
a_ptIdxes Array of point indices filled by this method. The indices correspond to locations in the m_pts vector.
Definition at line 494 of file GmTriSearch.cpp.
References xmlog::debug, m_tris, and XM_LOG.
SetPtActivity()
void xms::GmTriSearchImpl::SetPtActivity (DynBitset & a_activity) override virtual
Modifies the activity bitset of the points.
Parameters
a_activity bitset of the activity of the points
Definition at line 314 of file GmTriSearch.cpp.
References m_pts, m_triActivity, m_tris, and XM_ENSURE_TRUE_NO_ASSERT.
SetTriActivity()
void xms::GmTriSearchImpl::SetTriActivity (DynBitset & a_activity) override virtual
Modifies the activity bitset of the triangles.
Parameters
a_activity bitset of the activity of the points
Definition at line 334 of file GmTriSearch.cpp.
References m_triActivity, m_tris, and XM_ENSURE_TRUE_NO_ASSERT.
ToString()
std::string xms::GmTriSearchImpl::ToString () const override virtual
Write the internals to a string.
Returns
The string.
Definition at line 475 of file GmTriSearch.cpp.
References m_max, m_min, m_pts, m_triActivity, m_tris, and VecToStream().
TriContainingPt()
int xms::GmTriSearchImpl::TriContainingPt (const Pt3d & a_pt) override virtual
Find the triangle containing the point.
Parameters
a_pt Location used to find a triangle.
Returns
Index of triangle containing a_pt. If XM_NONE is returned then no triangle contained the point.
Definition at line 375 of file GmTriSearch.cpp.
References FindTriangle().
Referenced by TriSearchUnitTests::testSmsCase1(), and TriSearchUnitTests::testTouch().
TriEnvelopesOverlap()
void xms::GmTriSearchImpl::TriEnvelopesOverlap (const Pt3d & a_pMin, const Pt3d & a_pMax, std::vector< int > & a_tris) override virtual
Find all triangles whose envelope overlaps the envelope defined by a_pMin and a_pMax.
Parameters
a_pMin min x,y location of the box
a_pMax max x,y location of the box
a_tris The indices to triangles whose envelope intersects with the input envelope.
Definition at line 407 of file GmTriSearch.cpp.
References m_rTree, and xms::Pt3< T >::z.
Referenced by TriSearchUnitTests::testTriEnvelopesOverlap().
TriEnvelopsContainingPt()
void xms::GmTriSearchImpl::TriEnvelopsContainingPt (const Pt3d & a_pt, std::vector< int > & a_tris) override virtual
Find all triangles whose envelope contains the point.
Parameters
a_pt Location used to find a triangle.
a_tris The indices to triangles whose envelop contains the point
Definition at line 386 of file GmTriSearch.cpp.
References m_rTree, xms::Pt3< T >::x, and xms::Pt3< T >::y.
TrisToSearch()
void xms::GmTriSearchImpl::TrisToSearch (BSHP< std::vector< Pt3d >> a_pts, BSHP< std::vector< int >> a_tris) override virtual
Adds the triangles to the class.
Parameters
a_pts Array of point locations.
a_tris Array of triangles that references the a_pts array. This array will have a size that is a multiple of 3. The first 3 locations in array represent the first triangle and will have indices that correspond to locations in the a_pts array.
Definition at line 264 of file GmTriSearch.cpp.
References CreateRTree(), m_cache, m_pts, m_rTree, and m_tris.
Referenced by TriSearchUnitTests::testSmsCase1(), TriSearchUnitTests::testTouch(), and TriSearchUnitTests::testTriEnvelopesOverlap().
Member Data Documentation
m_cache
boost::unordered_map<size_t, BarycentricVals> xms::GmTriSearchImpl::m_cache
we create a cache of these for faster interp the second time we hit the triangle
Definition at line 171 of file GmTriSearch.cpp.
Referenced by GetTriBarycentricVals(), and TrisToSearch().
The documentation for this class was generated from the following file:
/home/conan/xmsinterp/geometry/GmTriSearch.cpp