xmsinterp: xms::GmExtents2d Class Reference
xms::GmExtents2d Class Reference
2D geometric extents (min/max).
Public Member Functions
GmExtents2d ()
constructor
GmExtents2d (const GmExtents3d &a_extents)
constructor
GmExtents2d (const Pt2d &a_min, const Pt2d &a_max)
constructor
GmExtents2d (const Pt3d &a_min, const Pt3d &a_max)
constructor
virtual ~GmExtents2d ()
destructor
void operator+= (const GmExtents2d &a_rhs)
operator +=
virtual void AddToExtents (const Pt3d &pt)
Add a point to the extents.
template<class ItrType >
void Add (ItrType a_begin, ItrType a_end)
Adds a range defined by two iterators to the extents.
bool IsValid ()
If we don't have any data we return false.
bool Overlap (const GmExtents2d &a_b) const
Test to see if two extents overlap.
void Clear ()
Resets the extents to defaults. IsValid will return false.
void GetExtents (double *a_MinX, double *a_MaxX, double *a_MinY, double *a_MaxY)
Gets the extents via the parameters.
void GetExtents (Pt3d &a_dMin, Pt3d &a_dMax)
Gets the extents via the parameters.
double GetMinX () const
Gets the minimum x.
double GetMaxX () const
Gets the maximum x.
double GetMinY () const
Gets the minimum y.
double GetMaxY () const
Gets the maximum y.
Pt2d GetMin () const
Gets the minimum.
Pt2d GetMax () const
Gets the maximum.
void Set (const Pt2d &a_min, const Pt2d &a_max)
Sets the min/max.
template<typename Archive >
void serialize (Archive &archive, const unsigned int version)
Boost serialize function.
Static Public Member Functions
static void SetTolerance (double a_Tol)
Sets the tolerance to use.
static double GetTolerance ()
Gets the tolerance in use.
Protected Attributes
Pt2d m_min
Minimum, maximum extents.
Pt2d m_max
Maximum, maximum extents.
Static Protected Attributes
static double m_tolerance
Tolerance used in comparisons.
Detailed Description
2D geometric extents (min/max).
Definition at line 37 of file GmExtents.h.
Constructor & Destructor Documentation
xms::GmExtents2d::GmExtents2d (const GmExtents3d & a_extents) explicit
constructor
Parameters
[in] a_extents GmExtents3d
Definition at line 49 of file GmExtents.cpp.
References xms::GmExtents3d::GetMax(), xms::GmExtents3d::GetMin(), m_max, and m_min.
xms::GmExtents2d::GmExtents2d (const Pt2d & a_min, const Pt2d & a_max)
constructor
Parameters
[in] a_min Minimum extents.
[in] a_max Maximum extents.
Definition at line 59 of file GmExtents.cpp.
xms::GmExtents2d::GmExtents2d (const Pt3d & a_min, const Pt3d & a_max)
constructor
Parameters
[in] a_min Minimum extents.
[in] a_max Maximum extents.
Definition at line 69 of file GmExtents.cpp.
Member Function Documentation
template<typename ItrType > void xms::GmExtents2d::Add (ItrType a_begin, ItrType a_end)
Adds a range defined by two iterators to the extents.
Parameters
[in] a_begin Start of range.
[in] a_end End of range.
Definition at line 84 of file GmExtents.h.
References AddToExtents().
void xms::GmExtents2d::AddToExtents (const Pt3d & pt) virtual
Add a point to the extents.
Parameters
[in] pt A point
Definition at line 95 of file GmExtents.cpp.
References m_max, m_min, xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt2< T >::y.
Referenced by Add(), and GmExtents3dUnitTests::testOverlapping().
void xms::GmExtents2d::GetExtents (double * a_MinX, double * a_MaxX, double * a_MinY, double * a_MaxY)
Gets the extents via the parameters.
Parameters
[out] a_MinX Minimum x.
[out] a_MaxX Maximum x.
[out] a_MinY Minimum y.
[out] a_MaxY Maximum y.
Definition at line 173 of file GmExtents.cpp.
References m_max, m_min, xms::Pt2< T >::x, and xms::Pt2< T >::y.
void xms::GmExtents2d::GetExtents (Pt3d & a_dMin, Pt3d & a_dMax)
Gets the extents via the parameters.
Parameters
[out] a_dMin Minimum.
[out] a_dMax Maximum.
Definition at line 197 of file GmExtents.cpp.
References m_max, and m_min.
Pt2d xms::GmExtents2d::GetMax () const
Gets the maximum.
Returns
Maximum.
Definition at line 246 of file GmExtents.cpp.
References m_max.
Referenced by xms::GmExtents3d::GmExtents3d().
double xms::GmExtents2d::GetMaxX () const
Gets the maximum x.
Returns
Maximum x.
Definition at line 214 of file GmExtents.cpp.
References m_max, and xms::Pt2< T >::x.
double xms::GmExtents2d::GetMaxY () const
Gets the maximum y.
Returns
Maximum y.
Definition at line 230 of file GmExtents.cpp.
References m_max, and xms::Pt2< T >::y.
Pt2d xms::GmExtents2d::GetMin () const
Gets the minimum.
Returns
Minimum.
Definition at line 238 of file GmExtents.cpp.
References m_min.
Referenced by xms::GmExtents3d::GmExtents3d().
double xms::GmExtents2d::GetMinX () const
Gets the minimum x.
Returns
Minimum x.
Definition at line 206 of file GmExtents.cpp.
References m_min, and xms::Pt2< T >::x.
double xms::GmExtents2d::GetMinY () const
Gets the minimum y.
Returns
Minimum y.
Definition at line 222 of file GmExtents.cpp.
References m_min, and xms::Pt2< T >::y.
double xms::GmExtents2d::GetTolerance () static
Gets the tolerance in use.
Returns
tolerance.
Definition at line 124 of file GmExtents.cpp.
References m_tolerance.
Referenced by GmExtents3dUnitTests::testOverlapping().
bool xms::GmExtents2d::IsValid ()
If we don't have any data we return false.
Returns
true if we have data.
Definition at line 108 of file GmExtents.cpp.
References m_max, m_min, and xms::Pt2< T >::x.
Referenced by GmExtents3dUnitTests::testOverlapping().
void xms::GmExtents2d::operator+= (const GmExtents2d & a_rhs)
operator +=
Parameters
[in] a_rhs GmExtents2d
Definition at line 84 of file GmExtents.cpp.
References m_max, m_min, xms::Pt2< T >::x, and xms::Pt2< T >::y.
bool xms::GmExtents2d::Overlap (const GmExtents2d & a_b) const
Test to see if two extents overlap.
Parameters
[in] a_b The other extents.
Returns
true if they overlap.
Definition at line 133 of file GmExtents.cpp.
References m_max, m_min, m_tolerance, xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by GmExtents3dUnitTests::testOverlapping().
template<typename Archive > void xms::GmExtents2d::serialize (Archive & archive, const unsigned int version)
Boost serialize function.
Parameters
[in,out] archive An archive.
[in] version The version number.
Definition at line 99 of file GmExtents.h.
References m_max, m_min, and m_tolerance.
void xms::GmExtents2d::Set (const Pt2d & a_min, const Pt2d & a_max)
Sets the min/max.
Parameters
[in] a_min The minimum extents.
[in] a_max The maximum extents.
Definition at line 255 of file GmExtents.cpp.
References m_max, and m_min.
void xms::GmExtents2d::SetTolerance (double a_Tol) static
Sets the tolerance to use.
Parameters
[in] a_Tol The tolerance.
Definition at line 116 of file GmExtents.cpp.
References m_tolerance.
Member Data Documentation
double xms::GmExtents2d::m_tolerance static protected
Tolerance used in comparisons.
Tolerance. Static ?
Definition at line 75 of file GmExtents.h.
Referenced by GetTolerance(), Overlap(), serialize(), and SetTolerance().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/geometry/GmExtents.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/geometry/GmExtents.cpp