xmsinterp: xms::InterpIdw Class Reference
xms::InterpIdw Class Reference
Class that performs inverse distance weighted interpolation.
#include <InterpIdw.h>
Public Types
enum WeightEnum { CLASSIC, MODIFIED }
Weight calculation method enumeration.
enum NodalFuncEnum { CONSTANT, GRAD_PLANE, QUADRATIC }
Nodal fuction type enumeration.
Static Public Member Functions
static BSHP< InterpIdw > New ()
Creates an InterpIdw class.
Detailed Description
Class that performs inverse distance weighted interpolation.
See Also
InterpIdwImpl
Definition at line 29 of file InterpIdw.h.
Member Function Documentation
BSHP< InterpIdw > xms::InterpIdw::New () static
Creates an InterpIdw class.
Returns
Shared pointer to InterpIdw.
Definition at line 232 of file InterpIdw.cpp.
Referenced by TutInterpolationIntermediateTests::test_Example_IDW(), InterpIdwUnitTests::testCreateClass(), InterpIdwUnitTests::testInterp2d_a(), InterpIdwUnitTests::testInterp2d_b(), InterpIdwUnitTests::testInterp2d_c(), InterpIdwUnitTests::testInterp2d_d(), InterpIdwUnitTests::testInterp2d_e(), InterpIdwUnitTests::testInterp2d_f(), InterpIdwUnitTests::testInterp3d(), and InterpIdwUnitTests::testInterpToPts().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/interpolate/InterpIdw.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/interpolate/InterpIdw.cpp