xmsinterp: xms::ThreadMgrImpl Class Reference
xms::ThreadMgrImpl Class Reference
Implmentation of ThreadMgr.
Classes
struct myThread
convenience struct for threads
Public Member Functions
ThreadMgrImpl ()
Constructor.
void SetThreadLoopClass (BSHP< ThreadLoop > a_) override
void ExplicitlySetNumThreads (int a_nThreads) override
void RunThreads (int a_nIter) override
Executes the threads.
void SetObserver (BSHP< Observer > a_prog) override
std::vector< BSHP< ThreadLoop > > Threads ()
Gets the threads managed by this class.
void SetupThreads ()
Sets up the threads.
void MonitorThreads ()
Monitors the progress of all the threads.
void FinishThreads ()
When all iterations are complete this terminates the threads.
Public Attributes
BSHP< ThreadLoop > m_threader
the worker class that is duplicated to run in multiple threads
BSHP< Observer > m_prog
observes the threads and gives feedback of % complete
int m_nThread
number of threads running
int m_nIter
total number of iterations for all threads combined
VecInt m_beg
starting index for each thread
VecInt m_thrdNumIter
number of iterations for each thread
VecInt m_counts
number of completed iterations for each thread
std::vector< myThread > m_vMyThread
vector of created threads
std::vector< boost::thread > m_vThreads
actual boost threads that are run
Additional Inherited Members
Static Public Member Functions inherited from xms::ThreadMgr
static BSHP< ThreadMgr > New ()
Creates a ThreadMgr.
Protected Member Functions inherited from xms::ThreadMgr
ThreadMgr ()
constructor
Detailed Description
Implmentation of ThreadMgr.
Class to manage multiple threads using boost.
Definition at line 39 of file ThreadMgr.cpp.
Member Function Documentation
void xms::ThreadMgrImpl::ExplicitlySetNumThreads (int a_nThreads) inline override virtual
Parameters
a_nThreads number of threads.
Implements xms::ThreadMgr.
Definition at line 67 of file ThreadMgr.cpp.
References m_nThread.
void xms::ThreadMgrImpl::RunThreads (int a_nIter) override virtual
Executes the threads.
Parameters
[in] a_nIter Total number of iterations for the threads to execute.
Implements xms::ThreadMgr.
Definition at line 140 of file ThreadMgr.cpp.
References FinishThreads(), m_nIter, m_nThread, MonitorThreads(), and SetupThreads().
void xms::ThreadMgrImpl::SetObserver (BSHP< Observer > a_prog) inline override virtual
Parameters
a_prog An observer
Implements xms::ThreadMgr.
Definition at line 70 of file ThreadMgr.cpp.
References m_prog.
void xms::ThreadMgrImpl::SetThreadLoopClass (BSHP< ThreadLoop > a_) inline override virtual
Parameters
a_ ThreadLoop.
Implements xms::ThreadMgr.
Definition at line 65 of file ThreadMgr.cpp.
References m_threader.
std::vector< BSHP< ThreadLoop > > xms::ThreadMgrImpl::Threads () virtual
Gets the threads managed by this class.
Returns
A Vector of threads managed by this class
Implements xms::ThreadMgr.
Definition at line 127 of file ThreadMgr.cpp.
References m_vMyThread.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/thread/ThreadMgr.cpp