xmsinterp: xms::ThreadMgr Class Reference
xms::ThreadMgr Class Reference abstract
Manages a multi-threaded process.
#include <ThreadMgr.h>
Public Member Functions
virtual void SetThreadLoopClass (BSHP< ThreadLoop > a_)=0
virtual void ExplicitlySetNumThreads (int a_nThreads)=0
virtual void RunThreads (int a_nIter)=0
virtual void SetObserver (BSHP< Observer > a_prog)=0
virtual std::vector< BSHP
< ThreadLoop > > Threads ()=0
Static Public Member Functions
static BSHP< ThreadMgr > New ()
Creates a ThreadMgr.
Protected Member Functions
ThreadMgr ()
constructor
Private Member Functions
XM_DISALLOW_COPY_AND_ASSIGN (ThreadMgr)
prevent copy/assign compiler generated functions
Detailed Description
Manages a multi-threaded process.
See Also
ThreadMgrImpl
Definition at line 28 of file ThreadMgr.h.
Member Function Documentation
virtual void xms::ThreadMgr::ExplicitlySetNumThreads (int a_nThreads) pure virtual
Don't have to call this and will use all processors
Parameters
a_nThreads Number of threads.
Implemented in xms::ThreadMgrImpl.
BSHP< ThreadMgr > xms::ThreadMgr::New () static
Creates a ThreadMgr.
Returns
shared pointer to ThreadMgr
Definition at line 106 of file ThreadMgr.cpp.
References xms::ThreadMgrImpl::ThreadMgrImpl().
Referenced by xms::NodalFuncImpl::ComputeNodalFuncs(), and xms::InterpIdwImpl::InterpToPts().
virtual void xms::ThreadMgr::RunThreads (int a_nIter) pure virtual
Execute the code in multiple threads
Parameters
a_nIter Total number of iterations for the threads to execute.
Implemented in xms::ThreadMgrImpl.
virtual void xms::ThreadMgr::SetObserver (BSHP< Observer > a_prog) pure virtual
To provide gui feedback
Parameters
a_prog Observer.
Implemented in xms::ThreadMgrImpl.
virtual void xms::ThreadMgr::SetThreadLoopClass (BSHP< ThreadLoop > a_) pure virtual
class that does the work
Parameters
a_ ThreadLoop class.
Implemented in xms::ThreadMgrImpl.
virtual std::vector<BSHP<ThreadLoop> > xms::ThreadMgr::Threads () pure virtual
Vector of threads managed by this class
Returns
Vector of threads managed by this class
Implemented in xms::ThreadMgrImpl.
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/thread/ThreadMgr.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/thread/ThreadMgr.cpp