xmsinterp: xms::TrTriangulator Class Reference
xms::TrTriangulator Class Reference
Base class used to derive a class to triangulate points.
Public Member Functions
TrTriangulator ()
Constructor.
virtual ~TrTriangulator ()
Destructor.
bool Triangulate ()
Triangulate the points into a tin.
Detailed Description
Base class used to derive a class to triangulate points.
See Also
TrTriangulatorPoints This class can be used to pass triangle based data to be consumed however the derived class prefers. Sometimes the point information will be provided and will need to be handled by derived classes. Other times (like in triangulation) it is assumed that the point data has already been stored for the target.
Definition at line 33 of file TrTriangulator.h.
Member Function Documentation
bool xms::TrTriangulator::Triangulate ()
Triangulate the points into a tin.
Returns
true on success.
Definition at line 55 of file TrTriangulator.cpp.
Referenced by TrAutoFixFourTrianglePtsUnitTests::test1(), TrBreaklineAdderUnitTests::test1(), TrTinUnitTests::testSwap(), trBuildTestTin6(), and trBuildTestTin7().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/triangulate/TrTriangulator.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/triangulate/TrTriangulator.cpp