xmsinterp: xms::InterpLinearImpl Class Reference
xms::InterpLinearImpl Class Reference
Implementation of InterpLinear.
Public Member Functions
virtual void SetPtsTris (BSHP< VecPt3d > a_, BSHP< VecInt > a_tris) override
Adds the triangles to the class.
virtual void SetScalars (const float *a_scalar, size_t a_n) override
Set the scalars that will be used to interpolate from.
virtual void SetScalars (BSHP< VecFlt > a_scalar) override
Set the scalars that will be used to interpolate from.
virtual void SetPtActivity (DynBitset &a_activity) override
Modifies the activity bitset of the class.
virtual void SetTriActivity (DynBitset &a_activity) override
Modifies the activity bitset of the class.
virtual const BSHP< VecPt3d > GetPts () const override
Returns shared pointer to points vector.
virtual const BSHP< VecInt > GetTris () const override
Returns shared pointer to triangles vector.
virtual const BSHP< VecFlt > GetScalars () const override
Returns shared pointer to scalars vector.
virtual DynBitset GetPtActivity () const override
Returns bitset of point activity.
virtual DynBitset GetTriActivity () const override
Returns bitset of triangle activity.
virtual float InterpToPt (const Pt3d &a_pt) override
Use the stored triangles to interpolate to a point. Returns extrapolation value if the point is outside the triangles.
virtual void InterpToPts (const VecPt3d &a_pts, VecFlt &a_scalars) override
Calls InterpToPt in a loop.
virtual int TriContainingPt (const Pt3d &a_pt) override
Find the triangle containing the point.
virtual void TriEnvelopsContainingPt (const Pt3d &a_pt, VecInt &a_tris) override
Find all triangles whose envelop contains the point.
virtual bool InterpWeights (const Pt3d &a_pt, VecInt &a_idxs, VecDbl &a_wts) override
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
float CloughTocherInterp (VecInt &a_idxs, const Pt3d &a_pt)
uses Clough Tocher interpolation method to get the interpolated val
float NatNeighInterp (const Pt3d &a_pt)
uses Natural Neighbor interpolation method to get the interpolated val
virtual void SetExtrapVal (double a_val) override
Set the constant extrapolation value.
virtual void SetTrunc (double a_sMax, double a_sMin) override
Set the truncation values for the interpolation and turn on truncation.
virtual void SetUseCloughTocher (bool a_, BSHP< Observer > a_prog) override
Set the class to use the Clough Tocher interpolation method. This is a legacy feature from GMS. Compare to linear.
virtual void SetUseNatNeigh (bool a_, int a_nodalFunc, int a_ndFuncOpt, int a_ndFuncNumNearestPts, bool a_blendWeights, BSHP< Observer > a_prog) override
Set the class to use natural neighbor (NN) interpolation.
virtual double GetExtrapVal () const
get extrapolation value
virtual bool GetTruncateInterpolatedValues () const
get the option to truncate interpolated values
virtual double GetTruncMin () const
get minimum truncation value
virtual double GetTruncMax () const
get the maximum truncation value
virtual bool GetUseCloughTocher () const
get the option for using Clough Tocher interpolation
virtual bool GetUseNatNeigh () const
get the option for using Natural Neighbor interpolation
virtual int GetNatNeighNodalFunc () const
get the value for the Natural Neighbor nodal function
virtual int GetNatNeighNodalFuncNearestPtsOption () const
get the option for the Natural Neighbor nodal function nearest points. Nearest points or nearest natural neighbors.
virtual int GetNatNeighNodalFuncNumNearestPts () const
get the value for the number of nearest points to use when calculating the nodal function
virtual bool GetNatNeighBlendWeights () const
get the option for blending weights when using Natural Neighbor
BSHP< GmPtSearch > CreatePtSearch ()
Creates a GmPtSearch class to be used for nodal function generation.
void RecalcNodalFunc ()
Resets some members of the class.
virtual std::string ToString () const override
Write the internals to a string.
Protected Attributes
BSHP< GmTriSearch > m_triSearch
spatial index for searching triangles
BSHP< VecPt3d > m_pts
pt locations that make up triangles
BSHP< VecInt > m_tris
triangles referencing indexes of pts
BSHP< VecFlt > m_scalar
Scalars we're interpolating from.
double m_extrap
Extrapolation value.
bool m_trunc
flag to indicate if truncation is on
double m_truncMax
Maximum truncation value. All interpolated values will be <=.
double m_truncMin
Minimum truncation value. All interpolated values will be >=.
bool m_cloughTocher
flag indicating clough tocher interpolation will be used
bool m_natNeigh
flag indicating that natural neighbor interpolation will be used
BSHP< NodalFunc > m_nodal
Nodal function (constant, gradient plane, quadratic)
BSHP< InterpCt > m_ct
Clough Tocher interpolation class.
BSHP< InterpNatNeigh > m_nn
Natural neighbor interpolation class.
std::string m_idString
identification for comparison with other Interp classes
Additional Inherited Members
Static Public Member Functions inherited from xms::InterpLinear
static BSHP< InterpLinear > New ()
Creates an TriSearch class.
Detailed Description
Implementation of InterpLinear.
Linear interpolation from a set of triangles Uses the boost RTree for queries.
Definition at line 50 of file InterpLinear.cpp.
Member Function Documentation
CloughTocherInterp()
float xms::InterpLinearImpl::CloughTocherInterp (VecInt & a_idxs, const Pt3d & a_pt)
uses Clough Tocher interpolation method to get the interpolated val
Parameters
a_idxs Indices to the points that form the triangle that a_pt is inside of.
a_pt Location that is interpolated to.
Returns
Interpolated value at a_pt.
Definition at line 409 of file InterpLinear.cpp.
References m_ct.
Referenced by InterpToPt().
CreatePtSearch()
BSHP< GmPtSearch > xms::InterpLinearImpl::CreatePtSearch ()
Creates a GmPtSearch class to be used for nodal function generation.
Returns
GmPtSearch.
Definition at line 518 of file InterpLinear.cpp.
References m_pts, m_triSearch, and xms::GmPtSearch::New().
Referenced by SetUseCloughTocher(), and SetUseNatNeigh().
GetExtrapVal()
virtual double xms::InterpLinearImpl::GetExtrapVal () const inline virtual
get extrapolation value
Returns
the extrapolation value
Definition at line 93 of file InterpLinear.cpp.
References m_extrap.
GetNatNeighBlendWeights()
virtual bool xms::InterpLinearImpl::GetNatNeighBlendWeights () const inline virtual
get the option for blending weights when using Natural Neighbor
Returns
the option for blending weights when using Natural Neighbor
Definition at line 137 of file InterpLinear.cpp.
References m_nodal.
GetNatNeighNodalFunc()
virtual int xms::InterpLinearImpl::GetNatNeighNodalFunc () const inline virtual
get the value for the Natural Neighbor nodal function
Returns
the value for the Natural Neighbor nodal function
Definition at line 111 of file InterpLinear.cpp.
References m_nodal.
GetNatNeighNodalFuncNearestPtsOption()
virtual int xms::InterpLinearImpl::GetNatNeighNodalFuncNearestPtsOption () const inline virtual
get the option for the Natural Neighbor nodal function nearest points. Nearest points or nearest natural neighbors.
Returns
the option for the Natural Neighbor nodal function nearest points.
Definition at line 120 of file InterpLinear.cpp.
References m_nodal.
GetNatNeighNodalFuncNumNearestPts()
virtual int xms::InterpLinearImpl::GetNatNeighNodalFuncNumNearestPts () const inline virtual
get the value for the number of nearest points to use when calculating the nodal function
Returns
the value for the number of nearest points
Definition at line 129 of file InterpLinear.cpp.
References m_nodal.
GetPtActivity()
DynBitset xms::InterpLinearImpl::GetPtActivity () const override virtual
Returns bitset of point activity.
Returns
Returns bitset of point activity
Definition at line 303 of file InterpLinear.cpp.
References m_triSearch.
GetPts()
const BSHP< VecPt3d > xms::InterpLinearImpl::GetPts () const override virtual
Returns shared pointer to points vector.
Returns
Shared pointer to points vector.
Definition at line 279 of file InterpLinear.cpp.
References m_pts.
GetScalars()
const BSHP< VecFlt > xms::InterpLinearImpl::GetScalars () const override virtual
Returns shared pointer to scalars vector.
Returns
Shared pointer to scalars vector.
Definition at line 295 of file InterpLinear.cpp.
References m_scalar.
GetTriActivity()
DynBitset xms::InterpLinearImpl::GetTriActivity () const override virtual
Returns bitset of triangle activity.
Returns
Returns bitset of triangle activity
Definition at line 311 of file InterpLinear.cpp.
References m_triSearch.
GetTris()
const BSHP< VecInt > xms::InterpLinearImpl::GetTris () const override virtual
Returns shared pointer to triangles vector.
Returns
Shared pointer to triangles vector.
Definition at line 287 of file InterpLinear.cpp.
References m_tris.
GetTruncateInterpolatedValues()
virtual bool xms::InterpLinearImpl::GetTruncateInterpolatedValues () const inline virtual
get the option to truncate interpolated values
Returns
the option to truncate interpolated values
Definition at line 96 of file InterpLinear.cpp.
References m_trunc.
GetTruncMax()
virtual double xms::InterpLinearImpl::GetTruncMax () const inline virtual
get the maximum truncation value
Returns
the maximum truncation value
Definition at line 102 of file InterpLinear.cpp.
References m_truncMax.
GetTruncMin()
virtual double xms::InterpLinearImpl::GetTruncMin () const inline virtual
get minimum truncation value
Returns
the minimum truncation value
Definition at line 99 of file InterpLinear.cpp.
References m_truncMin.
GetUseCloughTocher()
virtual bool xms::InterpLinearImpl::GetUseCloughTocher () const inline virtual
get the option for using Clough Tocher interpolation
Returns
the option for using Clough Tocher interpolation
Definition at line 105 of file InterpLinear.cpp.
References m_cloughTocher.
GetUseNatNeigh()
virtual bool xms::InterpLinearImpl::GetUseNatNeigh () const inline virtual
get the option for using Natural Neighbor interpolation
Returns
the option for using Natural Neighbor interpolation
Definition at line 108 of file InterpLinear.cpp.
References m_natNeigh.
InterpToPt()
float xms::InterpLinearImpl::InterpToPt (const Pt3d & a_pt) override virtual
Use the stored triangles to interpolate to a point. Returns extrapolation value if the point is outside the triangles.
Parameters
a_pt Location that is interpolated to.
Returns
Interpolated value at a_pt.
Definition at line 321 of file InterpLinear.cpp.
References CloughTocherInterp(), EQ_TOL(), m_cloughTocher, m_extrap, m_natNeigh, m_triSearch, m_trunc, m_truncMax, m_truncMin, and NatNeighInterp().
Referenced by InterpToPts(), InterpLinearUnitTests::testCt(), InterpLinearUnitTests::testInterp(), and InterpLinearUnitTests::testOneTriangle().
InterpToPts()
void xms::InterpLinearImpl::InterpToPts (const VecPt3d & a_pts, VecFlt & a_scalars) override virtual
Calls InterpToPt in a loop.
Parameters
a_pts Locations of points.
a_scalars Interpolated scalar values at a_pts.
Definition at line 362 of file InterpLinear.cpp.
References InterpToPt().
InterpWeights()
bool xms::InterpLinearImpl::InterpWeights (const Pt3d & a_pt, VecInt & a_idxs, VecDbl & a_wts) override virtual
Use the stored triangles to get interpolation weights for a point. Returns false if the point is outside the triangles.
Parameters
a_pt Location that is interpolated to.
a_idxs Vector of triangle point indices filled in by this method.
a_wts Vector of triangle point weights filled in by this method.
Returns
false if a_pt is not inside of any triangle
Definition at line 398 of file InterpLinear.cpp.
References m_triSearch.
NatNeighInterp()
float xms::InterpLinearImpl::NatNeighInterp (const Pt3d & a_pt)
uses Natural Neighbor interpolation method to get the interpolated val
Parameters
a_pt Location that is interpolated to.
Returns
Interpolated value at a_pt.
Definition at line 420 of file InterpLinear.cpp.
References m_nn.
Referenced by InterpToPt().
SetExtrapVal()
void xms::InterpLinearImpl::SetExtrapVal (double a_val) override virtual
Set the constant extrapolation value.
Parameters
a_val The value assigned to extrapolated points
Definition at line 428 of file InterpLinear.cpp.
References m_extrap.
Referenced by InterpLinearUnitTests::testOneTriangle().
SetPtActivity()
void xms::InterpLinearImpl::SetPtActivity (DynBitset & a_activity) override virtual
Modifies the activity bitset of the class.
Parameters
a_activity bitset of the activity of the points
Definition at line 261 of file InterpLinear.cpp.
References m_triSearch, and RecalcNodalFunc().
SetPtsTris()
void xms::InterpLinearImpl::SetPtsTris (BSHP< VecPt3d > a_pts, BSHP< VecInt > a_tris) override virtual
Adds the triangles to the class.
Parameters
a_pts Array of point locations.
a_tris Array of triangles that references the a_pts array. This array will have a size that is a multiple of 3. The first 3 locations in array represent the first triangle and will have indices that correspond to locations in the a_pts array.
Definition at line 227 of file InterpLinear.cpp.
References m_pts, m_scalar, m_tris, and m_triSearch.
Referenced by InterpLinearUnitTests::testCt(), InterpLinearUnitTests::testInterp(), and InterpLinearUnitTests::testOneTriangle().
SetScalars() [1/2]
void xms::InterpLinearImpl::SetScalars (const float * a_scalar, size_t a_n) override virtual
Set the scalars that will be used to interpolate from.
Parameters
a_scalar Array of interpolation scalar values.
a_n Size of the array a_scalar.
Definition at line 241 of file InterpLinear.cpp.
References m_pts, m_scalar, RecalcNodalFunc(), and XM_ENSURE_TRUE.
SetScalars() [2/2]
void xms::InterpLinearImpl::SetScalars (BSHP< VecFlt > a_scalar) override virtual
Set the scalars that will be used to interpolate from.
Parameters
a_scalar Array of interpolation scalar values.
Definition at line 251 of file InterpLinear.cpp.
References m_pts, m_scalar, RecalcNodalFunc(), and XM_ENSURE_TRUE.
SetTriActivity()
void xms::InterpLinearImpl::SetTriActivity (DynBitset & a_activity) override virtual
Modifies the activity bitset of the class.
Parameters
a_activity bitset of the activity of the triangles
Definition at line 270 of file InterpLinear.cpp.
References m_triSearch, and RecalcNodalFunc().
SetTrunc()
void xms::InterpLinearImpl::SetTrunc (double a_sMax, double a_sMin) override virtual
Set the truncation values for the interpolation and turn on truncation.
Parameters
a_sMax The maximum value for truncation.
a_sMin The minimum value for truncation.
Definition at line 438 of file InterpLinear.cpp.
References m_trunc, m_truncMax, and m_truncMin.
Referenced by InterpLinearUnitTests::testCt().
SetUseCloughTocher()
void xms::InterpLinearImpl::SetUseCloughTocher (bool a_, BSHP< Observer > a_prog) override virtual
Set the class to use the Clough Tocher interpolation method. This is a legacy feature from GMS. Compare to linear.
Parameters
a_ True/False to indicate if CT should be used.
a_prog Progress bar to give users feed back on the set up process of CT. If you have a really large set of triangles this may take some time.
Definition at line 451 of file InterpLinear.cpp.
References CreatePtSearch(), xms::inAllScalarsEqual(), m_cloughTocher, m_ct, m_nodal, m_pts, m_scalar, m_triSearch, and xms::NodalFunc::New().
Referenced by InterpLinearUnitTests::testCt().
SetUseNatNeigh()
void xms::InterpLinearImpl::SetUseNatNeigh (bool a_, int a_nodalFunc, int a_ndFuncOpt, int a_ndFuncNumNearestPts, bool a_blendWeights, BSHP< Observer > a_prog) override virtual
Set the class to use natural neighbor (NN) interpolation.
Parameters
a_ True/False to indicate if NN should be used.
a_nodalFunc Indicates which nodal function to use.
a_ndFuncOpt Indicates options for the nearest points when computing the nodal functions.
a_ndFuncNumNearestPts The number of nearest points for nodal function computation.
a_blendWeights Option to use a blending function on the calculated weights.
a_prog Progress bar to give user feedback for generation of the nodal functions.
Definition at line 483 of file InterpLinear.cpp.
References CreatePtSearch(), xms::inAllScalarsEqual(), m_natNeigh, m_nn, m_nodal, m_pts, m_scalar, m_tris, m_triSearch, xms::InterpNatNeigh::New(), and xms::NodalFunc::New().
ToString()
std::string xms::InterpLinearImpl::ToString () const override virtual
Write the internals to a string.
Returns
The string.
Definition at line 540 of file InterpLinear.cpp.
References m_cloughTocher, m_ct, m_extrap, m_natNeigh, m_nn, m_nodal, m_pts, m_scalar, m_tris, m_triSearch, m_trunc, m_truncMax, m_truncMin, and VecToStream().
TriContainingPt()
int xms::InterpLinearImpl::TriContainingPt (const Pt3d & a_pt) override virtual
Find the triangle containing the point.
Parameters
a_pt Location used to find a triangle.
Returns
Index of triangle containing a_pt. If XM_NONE is returned then no triangle contained the point.
Definition at line 377 of file InterpLinear.cpp.
References m_triSearch.
TriEnvelopsContainingPt()
void xms::InterpLinearImpl::TriEnvelopsContainingPt (const Pt3d & a_pt, VecInt & a_tris) override virtual
Find all triangles whose envelop contains the point.
Parameters
a_pt Location used to find a triangle.
a_tris The indices to triangles whose envelop contains the point
Definition at line 386 of file InterpLinear.cpp.
References m_triSearch.
The documentation for this class was generated from the following file:
/home/conan/xmsinterp/interpolate/InterpLinear.cpp