xmsinterp: xms::InterpLinear Class Reference
xms::InterpLinear Class Reference
Class that performs linear interpolation.
#include <InterpLinear.h>
Static Public Member Functions
static BSHP< InterpLinear > New ()
Creates an TriSearch class.
Detailed Description
Class that performs linear interpolation.
See also
InterpLinearImpl
Definition at line 37 of file InterpLinear.h.
Member Function Documentation
New()
BSHP< InterpLinear > xms::InterpLinear::New () static
Creates an TriSearch class.
Returns
Shared pointer to InterpLinear.
Definition at line 176 of file InterpLinear.cpp.
Referenced by TutInterpolationIntermediateTests::test_Example_Linear(), TutInterpolationIntermediateTests::test_Example_NaturalNeighbor(), and InterpLinearUnitTests::testToString().
The documentation for this class was generated from the following files:
/home/conan/xmsinterp/interpolate/InterpLinear.h
/home/conan/xmsinterp/interpolate/InterpLinear.cpp