xmsinterp: xms::GmPolygon Class Reference
xms::GmPolygon Class Reference
Interface to a boost::geometry::polygon class.
#include <GmPolygon.h>
Public Member Functions
GmPolygon ()
Constructor.
virtual ~GmPolygon ()
Destructor.
Static Public Member Functions
static BSHP< GmPolygon > New ()
Creates a class.
Detailed Description
Interface to a boost::geometry::polygon class.
See Also
GmPolygonImpl
Definition at line 34 of file GmPolygon.h.
Member Function Documentation
BSHP< GmPolygon > xms::GmPolygon::New () static
Creates a class.
Returns
GmPolygon.
Definition at line 290 of file GmPolygon.cpp.
Referenced by xms::GmPolygonImpl::Intersection(), GmPointInPolyTester_GmPolygon::Setup(), GmPolygonUnitTests::testIntersection(), GmPolygonUnitTests::testNoHoles(), GmPolygonUnitTests::testUnion(), GmPolygonUnitTests::testWithHoles(), and xms::GmPolygonImpl::Union().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/geometry/GmPolygon.h
/home/travis/build/Aquaveo/xmsinterp/xmsinterp/geometry/GmPolygon.cpp