xmsinterp: /home/conan/xmsinterp/geometry/geoms.cpp File Reference
geoms.cpp File Reference
Functions dealing with geometry.
#include <xmsinterp/geometry/geoms.h>
#include <cfloat>
#include <algorithm>
#include <xmscore/math/math.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/points/pt.h>
#include <xmscore/stl/vector.h>
#include <xmsinterp/geometry/GmPolygon.h>
#include <xmscore/misc/xmstype.h>
#include <xmsinterp/triangulate/triangles.h>
#include <xmscore/misc/XmConst.h>
#include <boost/timer/timer.hpp>
#include <xmscore/testing/TestTools.h>
#include <xmsinterp/geometry/GmPolygon.t.h>
#include <xmsinterp/geometry/geoms.t.h>
#include <xmscore/misc/XmLog.h>
Classes
class GmPointInPolyTester_gmPointInPolygon2D
For testing point in polygon speed.
Functions
bool xms::gmPointInOrOnBox2d (const Pt3d &a_bMin, const Pt3d &a_bMax, const Pt3d &a_pt)
finds if a point is in or on a box in 2d
bool xms::gmBoxesOverlap2d (const Pt3d &a_b1Min, const Pt3d &a_b1Max, const Pt3d &a_b2Min, const Pt3d &a_b2Max)
finds if 2 boxes overlap in 2d
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3, double *a, double *b, double *c, double *d)
Calculates the plane coefficients for a triangle. Given point references calculate coefficents for plane (ax+by+cz+d=0).
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, double *a, double *b, double *c, double *d)
Calculates the plane coefficients for a triangle. Given point pointers calculate coefficents for plane (ax+by+cz+d=0).
double xms::gmMiddleZ (const VecPt3d &a_points)
Returns the z value halfway between the max and min z. Different from the average z (where many points can skew the average).
PtInOutOrOn_enum xms::gmPtInCircumcircle (const Pt3d &pt, Pt3d circumcirclePts[3])
Is a given point inside a circumcircle defined by three points?
double xms::gmXyDistanceSquared (const Pt3d &pt1, const Pt3d &pt2)
Calculate XY distance between two 3D points.
bool xms::gmCircumcircleWithTol (const Pt3d *pt1, const Pt3d *pt2, const Pt3d *pt3, double *xc, double *yc, double *r2, double tol)
Computes center & radius squared for circumcircle of triangle made by the three points.
int xms::gmCartToBary (const Pt3d *cart, const Pt3d *orig, double coef[6], int dir, Pt3d *bary)
Compute Barycentric coords for point. Use gmBaryPrepare to get the coefficients and direction.
int xms::gmBaryPrepare (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, const Pt3d *norm, Pt3d *orig, double coef[6], int *dir, bool flag)
For a tri - compute dir & coefs to compute Barycentric coords.
bool xms::gmColinearWithTol (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3, const double tol)
Returns true if (the three vertices are gmColinear. Result should be insensitive to the order of the vertices.
bool xms::gmIntersectLineSegmentsWithTol (const Pt3d &one1, const Pt3d &one2, const Pt3d &two1, const Pt3d &two2, double *xi, double *yi, double *zi1, double *zi2, double tol)
Intersects the plan projection of two line segments.
bool xms::gmCounterClockwiseTri (const Pt3d &vtx0, const Pt3d &vtx1, const Pt3d &vtx2)
Returns true if the triangle is wrapped counter clockwise.
double xms::gmCross2D (const double &dx1, const double &dy1, const double &dx2, const double &dy2)
Returns the cross product of two 2-d vectors.
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn, double a_magn, double a_magp)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
double xms::gmAngleBetweenEdges (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
double xms::gmAngleBetweenEdges (const Pt2d &p1, const Pt2d &p2, const Pt2d &p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
double xms::gmComputeDeviationInDirection (const Pt3d &a_p0, const Pt3d &a_p1, const Pt3d &a_p2)
Computes the deviation in direction from one seg to next seg 1 is from a_p0 to a_p1 seg 2 is from a_p1 to a_p2.
bool xms::gmOnLineWithTol (const Pt3d &p1, const Pt3d &p2, const double x, const double y, const double tol)
Determines if a point (x,y) is on the line defined by p1 and p2. Assumes p1 and p2 aren't the same.
bool xms::gmOnLineAndBetweenEndpointsWithTol (const Pt3d &a_pt1, const Pt3d &a_pt2, const double a_x, const double a_y, double a_tol)
determines if (x,y) is on the line passing through p1 & p2 and between p1 & p2.
void xms::gmAddToExtents (const Pt3d &a_pt, Pt3d &a_min, Pt3d &a_max)
Compares a_pt to a_min and a_max. If a_pt is less than a_min or greater than a_max, a_min and a_max are updated.
void xms::gmAddToExtents (const Pt3d &a_pt, Pt2d &a_min, Pt2d &a_max)
void xms::gmAddToExtents (const Pt2d &a_pt, Pt3d &a_min, Pt3d &a_max)
double xms::gmXyDistance (double x1, double y1, double x2, double y2)
Compute the 2d distance between 2 points.
double xms::gmXyDistance (const Pt3d &pt1, const Pt3d &pt2)
Turn_enum xms::gmTurn (const Pt3d &a_v1, const Pt3d &a_v2, const Pt3d &a_v3, double a_angtol)
Determine if angle a_v1, a_v2, a_v3 is a left turn, a right turn, colinear 180 degrees, or colinear 0 degrees.
Pt3d xms::gmComputeCentroid (const VecPt3d &a_points)
Computes the centroid of points (but not of a polygon). Shouldn't pass an empty vector (no checks are performed).
Pt3d xms::gmComputePolygonCentroid (const VecPt3d &pts)
Computes the plan view centroid of a non-self-intersecting polygon.
bool xms::gmLinesIntersect (const Pt3d &one1, const Pt3d &one2, const Pt3d &two1, const Pt3d &two2)
intersects the plan projection of two line segments (bad func name) segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
template<typename T >
int xms::gmPointInPolygon2D (const T *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
Determines whether (a_x, a_y) is inside=1, on=0, or outside=-1 the polygon defined by the given vertices.
int xms::gmPointInPolygon2D (const Pt3d *a_verts, size_t a_num, double a_x, double a_y)
int xms::gmPointInPolygon2D (const Pt3d *a_verts, size_t a_num, Pt3d a_pt)
int xms::gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt2d a_pt)
int xms::gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt3d a_pt)
int xms::gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt2i a_pt)
int xms::gmPointInPolygon2D (const VecPt3d &a_verts, const Pt3d &a_pt)
template int xms::gmPointInPolygon2D< Pt3d > (const Pt3d *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
template int xms::gmPointInPolygon2D< Pt2d > (const Pt2d *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
template int xms::gmPointInPolygon2D< Pt2i > (const Pt2i *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
double xms::gmComputeXyTol (const Pt3d &a_mn, const Pt3d &a_mx)
Given extents (min, max), compute a tolerance for the xy plane to be used with geometric functions.
double xms::gmXyTol (bool a_set, double a_value)
Get or set (set first time) global xy tolerance for float operations.
double xms::gmZTol (bool a_set, double a_value)
Get or set (set first time) global z tolerance for float operations.
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2, double tolerance)
Returns true if the points are equal to within gmXyTol().
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2)
bool xms::gmEqualPointsXY (const Pt2d &a_pt1, const Pt2d &a_pt2, double tol)
bool xms::gmEqualPointsXY (const Pt3d &a_pt1, const Pt3d &a_pt2, double tol)
bool xms::gmEqualPointsXY (const Pt2i &point1, const Pt2i &point2)
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2, double tolerance)
Returns true if the points are equal to within tolerance.
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2)
bool xms::gmEqualPointsXYZ (const Pt3d &pt1, const Pt3d &pt2, double tol)
bool xms::gmPointInTriangleWithTol (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, double x, double y, double tol)
Returns true if (x,y) is in the tri formed by p1, p2, p3.
bool xms::gmInsideOrOnLineWithTol (const Pt3d *p1, const Pt3d *p2, const Pt3d *inpoint, const double x, const double y, const double tol, double *dist)
Returns true if the (x,y) is on the line segment (p1,p2) or on the same side of the line as "inpoint". ASSERTs in debug if "inpoint" is on the line (within tol).
double xms::gmPolygonArea (const Pt3d *pts, size_t npoints)
Compute 2d planview projection of area of polygon.
VecPt3d xms::gmArrayToVecPt3d (double *a_array, int a_size)
Useful in testing to create a VecPt3d from a C array of xy pairs.
void xms::gmEnvelopeOfPts (const VecPt3d &a_pts, Pt3d &a_min, Pt3d &a_max)
Calculates the envelope of a vector of points.
void xms::gmOrderPointsCounterclockwise (const VecPt3d &a_pts, VecInt &a_ccwOrder, int a_startindex)
Orders array of points counter clockwise. Given non-empty array of points. array of point indices ordered counter clockwise based on the angle from the centroid where angle starts at point at startindex.
void xms::gmOrderPointsCounterclockwise (VecPt3d &a_pts)
Overload to gmOrderPointsCounterclockwise.
double xms::gmFindClosestPtOnSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt, Pt3d &a_newpt, const double a_tol)
Finds the closest point to another point on a segment.
double xms::gmPtDistanceAlongSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt, const double a_tol)
Finds the distance along a segment for the location closest to a_pt.
bool xms::gmInsideOfLineWithTol (const Pt3d &a_vertex1, const Pt3d &a_vertex2, const Pt3d &a_oppositevertex, const double a_x, const double a_y, const double a_tol)
Returns TRUE if the Point on the same side of the line (defined by vertex1 and vertex2) as oppositevertex.
void xms::gmExtents2D (const VecPt3d &a_points, Pt2d &a_min, Pt2d &a_max)
Get the 2D extents of a vector of points.
void xms::gmExtents2D (const VecPt3d &a_points, Pt3d &a_min, Pt3d &a_max)
void xms::gmExtents3D (const VecPt3d &a_points, Pt3d &a_min, Pt3d &a_max)
Get the 3D extents of a vector of points.
double xms::gmPerpendicularAngle (const Pt3d &a_pt1, const Pt3d &a_pt2)
Returns the angle in radians perpendicular to the two points.
double xms::gmBisectingAngle (const Pt3d &a_p1, const Pt3d &a_p2, const Pt3d &a_p3)
Returns the angle (0-2pi) which bisects the edges p2-p1 and p2-p3 based on a ccw rotation from edge 1 to edge 2.
void xms::gmComponentMagnitudes (double *a_x, double *a_y, double *a_mag, double *a_dir, bool a_tomagdir)
converts the magnitude and angle to xy components or vice versa
Pt3d xms::gmCreateVector (const Pt3d &a_p1, const Pt3d &a_p2)
creates a vector from a_p1 to a_p2
double xms::gmConvertAngleToBetween0And360 (double a_angle, bool a_InDegrees)
given an angle, this function will return the corresponding angle that matches it in the range of 0 deg to 360 deg
void xms::gmCross3D (const Pt3d &a_vec1, const Pt3d &a_vec2, Pt3d *a_vec3)
Perform a cross product of Pt3d's.
double xms::gmDot3D (const Pt3d &a_vec1, const Pt3d &a_vec2)
Perform a dot product of Pt3d's.
int xms::gmIntersectTriangleAndLineSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_t0, const Pt3d &a_t1, const Pt3d &a_t2, Pt3d &a_IntersectPt)
Determine if the line (described by a_pt1 and a_pt2) intersects the triangle (a_t0, a_t1, a_t2).
double xms::gm2DDistanceToLineWithTol (const Pt3d *a_pt1, const Pt3d *a_pt2, double a_x, double a_y, double a_tol)
return the xy distance from (a_x,a_y) to line through (a_pt1, a_pt2)
Detailed Description
Functions dealing with geometry.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file geoms.cpp.
Function Documentation
gm2DDistanceToLineWithTol()
double xms::gm2DDistanceToLineWithTol (const Pt3d * a_pt1, const Pt3d * a_pt2, double a_x, double a_y, double a_tol)
return the xy distance from (a_x,a_y) to line through (a_pt1, a_pt2)
Parameters
[in] a_pt1 first point of line segment
[in] a_pt2 second point of line segment
[in] a_x x location of point used to compute distance to line
[in] a_y y location of point used to compute distance to line
[in] a_tol tolerance used in geometric computations
Returns
distance from a_x,a_y to the line (a_pt1, a_pt2)
Definition at line 2112 of file geoms.cpp.
References xms::gm2DDistanceToLineWithTol(), and sqr().
Referenced by xms::gm2DDistanceToLineWithTol().
gmAddToExtents() [1/3]
void xms::gmAddToExtents (const Pt3d & a_pt, Pt3d & a_min, Pt3d & a_max)
Compares a_pt to a_min and a_max. If a_pt is less than a_min or greater than a_max, a_min and a_max are updated.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 762 of file geoms.cpp.
References xms::gmAddToExtents().
Referenced by xms::GmMultiPolyIntersectorImpl::BuildRTree(), xms::GmMultiPolyIntersectorImpl::CalculateBuffer(), xms::TrTinImpl::GetExtents(), xms::gmAddToExtents(), xms::gmExtents2D(), xms::gmExtents3D(), and xms::TrTriangulatorPoints::UpdateAreaTolerance().
gmAddToExtents() [2/3]
void xms::gmAddToExtents (const Pt3d & a_pt, Pt2d & a_min, Pt2d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 777 of file geoms.cpp.
References xms::gmAddToExtents().
gmAddToExtents() [3/3]
void xms::gmAddToExtents (const Pt2d & a_pt, Pt3d & a_min, Pt3d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 790 of file geoms.cpp.
References xms::gmAddToExtents().
gmAngleBetween2DVectors() [1/2]
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
Parameters
[in] dxp x of vector p.
[in] dyp y of vector p.
[in] dxn x of vector n.
[in] dyn y of vector n.
Returns
The angle.
Definition at line 578 of file geoms.cpp.
References xms::gmAngleBetween2DVectors(), and sqr().
Referenced by xms::gmAngleBetween2DVectors(), and xms::gmAngleBetweenEdges().
gmAngleBetween2DVectors() [2/2]
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn, double a_magn, double a_magp)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
Parameters
[in] dxp x of vector p.
[in] dyp y of vector p.
[in] dxn x of vector n.
[in] dyn y of vector n.
[in] a_magn Magnitude of n.
[in] a_magp Magnitude of p.
Returns
The angle.
Definition at line 597 of file geoms.cpp.
References xms::gmAngleBetween2DVectors(), xms::gmCross2D(), and XM_PI.
gmAngleBetweenEdges() [1/2]
double xms::gmAngleBetweenEdges (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
Returns
The angle.
Definition at line 630 of file geoms.cpp.
References xms::gmAngleBetween2DVectors(), and xms::gmAngleBetweenEdges().
Referenced by xms::gmAngleBetweenEdges(), and xms::TrTinImpl::SwapEdge().
gmAngleBetweenEdges() [2/2]
double xms::gmAngleBetweenEdges (const Pt2d & p1, const Pt2d & p2, const Pt2d & p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
Returns
The angle.
Definition at line 647 of file geoms.cpp.
References xms::gmAngleBetween2DVectors(), and xms::gmAngleBetweenEdges().
gmArrayToVecPt3d()
VecPt3d xms::gmArrayToVecPt3d (double * a_array, int a_size)
Useful in testing to create a VecPt3d from a C array of xy pairs.
Parameters
[in] a_array Array of xy pairs ([x][y][x][y]...).
[in] a_size Array size.
Returns
Vector of Pt3d.
Definition at line 1525 of file geoms.cpp.
References xms::gmArrayToVecPt3d().
Referenced by xms::gmArrayToVecPt3d().
gmBaryPrepare()
int xms::gmBaryPrepare (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, const Pt3d * norm, Pt3d * orig, double coef[6], int * dir, bool flag)
For a tri - compute dir & coefs to compute Barycentric coords.
Parameters
p1 = 1st point of triangle.
p2 = 2nd point of triangle.
p3 = 3rd point of triangle.
norm = triangle normal.
orig = triangle origin (min xyz of p1, p2 and p3).
coef = ?
dir = 0 if norm points to x, 1 if to y, 2 if to z.
flag = if true, origin will be computed from the triangle. If false, just calculate the coefficients and the origin is zero.
Returns
XM_SUCCESS or XM_FAILURE.
Definition at line 301 of file geoms.cpp.
References xms::gmBaryPrepare(), Mmin(), and XM_SUCCESS.
Referenced by xms::gmBaryPrepare(), and xms::iCartToBary().
gmBisectingAngle()
double xms::gmBisectingAngle (const Pt3d & a_p1, const Pt3d & a_p2, const Pt3d & a_p3)
Returns the angle (0-2pi) which bisects the edges p2-p1 and p2-p3 based on a ccw rotation from edge 1 to edge 2.
Parameters
[in] a_p1 The first point defining the edge (a_p1:a_p2)
[in] a_p2 The second point defining two edges (a_p1:a_p2, a_p2:a_p3)
[in] a_p3 The third point defining the edge (a_p2:a_p3)
Returns
angle that bisects the edges
Definition at line 1836 of file geoms.cpp.
References xms::gmBisectingAngle(), xms::gmCross2D(), sqr(), and XM_PI.
Referenced by xms::gmBisectingAngle().
gmBoxesOverlap2d()
bool xms::gmBoxesOverlap2d (const Pt3d & a_b1Min, const Pt3d & a_b1Max, const Pt3d & a_b2Min, const Pt3d & a_b2Max)
finds if 2 boxes overlap in 2d
Parameters
[in] a_b1Min Min x,y of first box
[in] a_b1Max Max x,y of first box
[in] a_b2Min Min x,y of second box
[in] a_b2Max Max x,y of second box
Returns
true if the boxes overlap
Definition at line 65 of file geoms.cpp.
References xms::gmBoxesOverlap2d().
Referenced by xms::gmBoxesOverlap2d().
gmCalculateNormalizedPlaneCoefficients() [1/2]
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3, double * a, double * b, double * c, double * d)
Calculates the plane coefficients for a triangle. Given point references calculate coefficents for plane (ax+by+cz+d=0).
Parameters
[in] p1 First point.
[in] p2 Second point.
[in] p3 Third point.
[out] a Coefficient a.
[out] b Coefficient b.
[out] c Coefficient c.
[out] d Coefficient d.
Definition at line 91 of file geoms.cpp.
References xms::gmCalculateNormalizedPlaneCoefficients().
Referenced by xms::gmCalculateNormalizedPlaneCoefficients().
gmCalculateNormalizedPlaneCoefficients() [2/2]
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, double * a, double * b, double * c, double * d)
Calculates the plane coefficients for a triangle. Given point pointers calculate coefficents for plane (ax+by+cz+d=0).
Parameters
[in] p1 First point.
[in] p2 Second point.
[in] p3 Third point.
[out] a Coefficient a.
[out] b Coefficient b.
[out] c Coefficient c.
[out] d Coefficient d.
Definition at line 113 of file geoms.cpp.
References xms::gmCalculateNormalizedPlaneCoefficients().
gmCartToBary()
int xms::gmCartToBary (const Pt3d * cart, const Pt3d * orig, double coef[6], int dir, Pt3d * bary)
Compute Barycentric coords for point. Use gmBaryPrepare to get the coefficients and direction.
Parameters
[in] cart cart?
[in] orig orig?
[in] coef 6 coefficients.
[in] dir Direction.
[out] bary point?
Returns
XM_SUCCESS (always it seems)
Definition at line 261 of file geoms.cpp.
References xms::gmCartToBary(), and XM_SUCCESS.
Referenced by xms::gmCartToBary(), and xms::iGetBarycentricCoords().
gmCircumcircleWithTol()
bool xms::gmCircumcircleWithTol (const Pt3d * pt1, const Pt3d * pt2, const Pt3d * pt3, double * xc, double * yc, double * r2, double tol)
Computes center & radius squared for circumcircle of triangle made by the three points.
Parameters
pt1 first of 3 locations defining a triangle
pt2 second of 3 locations defining a triangle
pt3 third of 3 locations defining a triangle
xc circumcenter x coord
yc circumcenter y coord
r2 radius squared of circumcircle
tol tolerance for geometric comparison
Returns
false on error (triangle has zero area), otherwise true
Definition at line 204 of file geoms.cpp.
References xms::gmCircumcircleWithTol(), and sqr().
Referenced by xms::InterpNatNeighImpl::FillCenterVec(), xms::gmCircumcircleWithTol(), xms::gmPtInCircumcircle(), and xms::InterpNatNeighImpl::HaleNnAddOuterEdge().
gmColinearWithTol()
bool xms::gmColinearWithTol (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3, const double tol)
Returns true if (the three vertices are gmColinear. Result should be insensitive to the order of the vertices.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
[in] tol Tolerance
Returns
true if colinear.
Definition at line 379 of file geoms.cpp.
References xms::gmColinearWithTol(), and xms::gmOnLineWithTol().
Referenced by xms::gmColinearWithTol(), and xms::gmIntersectLineSegmentsWithTol().
gmComponentMagnitudes()
void xms::gmComponentMagnitudes (double * a_x, double * a_y, double * a_mag, double * a_dir, bool a_tomagdir)
converts the magnitude and angle to xy components or vice versa
Parameters
[in,out] a_x vector x component either specified or calculated from a_mag, a_dir
[in,out] a_y vector y component either specified or calculated from a_mag, a_dir
[in,out] a_mag vector magnitude either specified or calculated from a_x, a_y
[in,out] a_dir vector direction (degrees) either specified or calculated from a_x, a_y
[in] a_tomagdir flag, when true a_x, a_y are used to calculate a_mag, a_dir; when false a_mag, a_dir are used to calculate a_x, a_y
Definition at line 1876 of file geoms.cpp.
References xms::gmComponentMagnitudes(), sqr(), XM_PI, and XM_ZERO_TOL.
Referenced by xms::gmComponentMagnitudes().
gmComputeCentroid()
Pt3d xms::gmComputeCentroid (const VecPt3d & a_points)
Computes the centroid of points (but not of a polygon). Shouldn't pass an empty vector (no checks are performed).
Parameters
[in] a_points Points.
Returns
Centroid.
Definition at line 870 of file geoms.cpp.
References xms::gmComputeCentroid().
Referenced by xms::gmComputeCentroid(), xms::GmMultiPolyIntersectionSorterTerse::RemoveDuplicateEdges(), and xms::trBuildGridTrianglePolys().
gmComputeDeviationInDirection()
double xms::gmComputeDeviationInDirection (const Pt3d & a_p0, const Pt3d & a_p1, const Pt3d & a_p2)
Computes the deviation in direction from one seg to next seg 1 is from a_p0 to a_p1 seg 2 is from a_p1 to a_p2.
Parameters
[in] a_p0 1st point on 1st segment.
[in] a_p1 2nd point on 1st segment and 1st point on second segment.
[in] a_p2 2nd point on 2nd segment.
Returns
Returns value between 0 and PI. note: magnitude zero would cause problem - return PI in this case returning PI would indicate that there could be discontinuity this is a streamlined version of gmAngleBetweenEdges that function
computes a directed internal difference
requires an extra cross product, several compares & multiplies this function still has the sqrt and acos, so maybe not a big deal
Definition at line 672 of file geoms.cpp.
References xms::gmComputeDeviationInDirection(), Mmax(), Mmin(), and XM_PI.
Referenced by xms::gmComputeDeviationInDirection().
gmComputePolygonCentroid()
Pt3d xms::gmComputePolygonCentroid (const VecPt3d & pts)
Computes the plan view centroid of a non-self-intersecting polygon.
Parameters
[in] pts Points.
Returns
Centroid.
Definition at line 883 of file geoms.cpp.
References xms::gmComputePolygonCentroid().
Referenced by xms::gmComputePolygonCentroid().
gmComputeXyTol()
double xms::gmComputeXyTol (const Pt3d & a_mn, const Pt3d & a_mx)
Given extents (min, max), compute a tolerance for the xy plane to be used with geometric functions.
Parameters
a_mn Minimum.
a_mx Maximum.
Returns
Tolerance.
Definition at line 1199 of file geoms.cpp.
References xms::gmComputeXyTol(), and xms::gmXyDistance().
Referenced by xms::TrBreaklineAdderImpl::ComputeTolerance(), xms::gmComputeXyTol(), and xms::TrTriangulatorPoints::UpdateAreaTolerance().
gmConvertAngleToBetween0And360()
double xms::gmConvertAngleToBetween0And360 (double a_angle, bool a_InDegrees)
given an angle, this function will return the corresponding angle that matches it in the range of 0 deg to 360 deg
Parameters
[in] a_angle The angle to convert to 0 to 360
[in] a_InDegrees Flag to tell if the angle is in degrees vs radians
Returns
an angle between 0 and 360
Definition at line 1932 of file geoms.cpp.
References xms::gmConvertAngleToBetween0And360(), GTEQ_TOL(), LT_TOL(), and XM_PI.
Referenced by xms::gmConvertAngleToBetween0And360().
gmCounterClockwiseTri()
bool xms::gmCounterClockwiseTri (const Pt3d & vtx0, const Pt3d & vtx1, const Pt3d & vtx2)
Returns true if the triangle is wrapped counter clockwise.
Parameters
[in] vtx0 Vertex 0.
[in] vtx1 Vertex 1.
[in] vtx2 Vertex 2.
Returns
true if vertex order is counter clockwise.
Definition at line 550 of file geoms.cpp.
References xms::gmCounterClockwiseTri(), and xms::trArea().
Referenced by xms::gmCounterClockwiseTri(), and xms::TrTinImpl::SwapEdge().
gmCreateVector()
Pt3d xms::gmCreateVector (const Pt3d & a_p1, const Pt3d & a_p2)
creates a vector from a_p1 to a_p2
Parameters
[in] a_p1 The first point
[in] a_p2 The second point
Returns
a vector with x,y,z components representing the direction from a_p1 to a_p2
Definition at line 1917 of file geoms.cpp.
References xms::gmCreateVector().
Referenced by xms::gmCreateVector().
gmCross2D()
double xms::gmCross2D (const double & dx1, const double & dy1, const double & dx2, const double & dy2)
Returns the cross product of two 2-d vectors.
Parameters
dx1 x component of vector 1
dy1 y component of vector 1
dx2 x component of vector 2
dy2 y component of vector 2
Returns
cross product of 2 vectors vector 1 = dx1i + dy1j vector 2 = dx2i + dy2j
Definition at line 565 of file geoms.cpp.
References xms::gmCross2D().
Referenced by xms::AnisotropicInterpolator::CrossProduct(), xms::gmAngleBetween2DVectors(), xms::gmBisectingAngle(), and xms::gmCross2D().
gmCross3D()
void xms::gmCross3D (const Pt3d & a_vec1, const Pt3d & a_vec2, Pt3d * a_vec3)
Perform a cross product of Pt3d's.
Parameters
[in] a_vec1 First vector to cross
[in] a_vec2 Second vector to cross
[out] a_vec3 Resulting cross product
Definition at line 1969 of file geoms.cpp.
References xms::gmCross3D().
Referenced by xms::gmCross3D(), and xms::gmIntersectTriangleAndLineSegment().
gmDot3D()
double xms::gmDot3D (const Pt3d & a_vec1, const Pt3d & a_vec2) inline
Perform a dot product of Pt3d's.
Parameters
[in] a_vec1 First vector to dot
[in] a_vec2 Second vector to dot
Returns
The dot product has the geometric interpretation as the length of the projection of a_vec1 onto the unit vector a_vec2 when the two vectors are placed so that their tails coincide.
Definition at line 1983 of file geoms.cpp.
References xms::gmDot3D().
Referenced by xms::gmDot3D(), and xms::gmIntersectTriangleAndLineSegment().
gmEnvelopeOfPts()
void xms::gmEnvelopeOfPts (const VecPt3d & a_pts, Pt3d & a_min, Pt3d & a_max)
Calculates the envelope of a vector of points.
Parameters
[in] a_pts Array of points
[out] a_min Min x,y,z of the points
[out] a_max Max x,y,z of the points
Definition at line 1541 of file geoms.cpp.
References xms::gmEnvelopeOfPts(), and XM_ENSURE_TRUE.
Referenced by xms::gmEnvelopeOfPts().
gmEqualPointsXY() [1/5]
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2, double tolerance)
Returns true if the points are equal to within gmXyTol().
Parameters
x1 x of point 1.
y1 y of point 1.
x2 x of point 2.
y2 y of point 2.
tolerance tolerance.
Returns
true if equal.
Definition at line 1245 of file geoms.cpp.
References xms::gmEqualPointsXY().
Referenced by xms::gmEqualPointsXY(), xms::gmInsideOfLineWithTol(), xms::gmInsideOrOnLineWithTol(), xms::gmIntersectLineSegmentsWithTol(), xms::gmOnLineWithTol(), and xms::GmMultiPolyIntersectorImpl::PointsOnSegment().
gmEqualPointsXY() [2/5]
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
x1 x of point 1.
y1 y of point 1.
x2 x of point 2.
y2 y of point 2.
Returns
true if equal.
Definition at line 1264 of file geoms.cpp.
References xms::gmEqualPointsXY(), and xms::gmXyTol().
gmEqualPointsXY() [3/5]
bool xms::gmEqualPointsXY (const Pt2d & a_pt1, const Pt2d & a_pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1275 of file geoms.cpp.
References xms::gmEqualPointsXY().
gmEqualPointsXY() [4/5]
bool xms::gmEqualPointsXY (const Pt3d & a_pt1, const Pt3d & a_pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1286 of file geoms.cpp.
References xms::gmEqualPointsXY().
gmEqualPointsXY() [5/5]
bool xms::gmEqualPointsXY (const Pt2i & point1, const Pt2i & point2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
point1 Point 1.
point2 Point 2.
Returns
true if equal within tolerance.
Definition at line 1296 of file geoms.cpp.
References xms::gmEqualPointsXY().
gmEqualPointsXYZ() [1/3]
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2, double tolerance)
Returns true if the points are equal to within tolerance.
Parameters
x1 x of point 1.
y1 y of point 1.
z1 z of point 1.
x2 x of point 2.
y2 y of point 2.
z2 z of point 2.
tolerance tolerance.
Returns
true if equal.
Definition at line 1313 of file geoms.cpp.
References xms::gmEqualPointsXYZ().
Referenced by xms::gmEqualPointsXYZ().
gmEqualPointsXYZ() [2/3]
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
x1 x of point 1.
y1 y of point 1.
z1 z of point 1.
x2 x of point 2.
y2 y of point 2.
z2 z of point 2.
Returns
true if equal within tolerance.
Definition at line 1335 of file geoms.cpp.
References xms::gmEqualPointsXYZ(), and xms::gmXyTol().
gmEqualPointsXYZ() [3/3]
bool xms::gmEqualPointsXYZ (const Pt3d & pt1, const Pt3d & pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
pt1 Point 1.
pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1346 of file geoms.cpp.
References xms::gmEqualPointsXYZ().
gmExtents2D() [1/2]
void xms::gmExtents2D (const VecPt3d & a_points, Pt2d & a_min, Pt2d & a_max)
Get the 2D extents of a vector of points.
Parameters
[in] a_points The points.
[out] a_min Minimum point (xy) of bounding rectangle.
[out] a_max Maximum point (xy) of bounding rectangle.
Definition at line 1756 of file geoms.cpp.
References xms::gmAddToExtents(), xms::gmExtents2D(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
Referenced by xms::gmExtents2D().
gmExtents2D() [2/2]
void xms::gmExtents2D (const VecPt3d & a_points, Pt3d & a_min, Pt3d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_points Vector of points.
[in,out] a_min Minimum value.
[in,out] a_max Maximum value.
Definition at line 1773 of file geoms.cpp.
References xms::gmAddToExtents(), xms::gmExtents2D(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
gmExtents3D()
void xms::gmExtents3D (const VecPt3d & a_points, Pt3d & a_min, Pt3d & a_max)
Get the 3D extents of a vector of points.
Parameters
[in] a_points The points.
[out] a_min Minimum point (xyz) of bounding box.
[out] a_max Maximum point (xyz) of bounding box.
Definition at line 1791 of file geoms.cpp.
References xms::gmAddToExtents(), xms::gmExtents3D(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
Referenced by xms::gmExtents3D().
gmFindClosestPtOnSegment()
double xms::gmFindClosestPtOnSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt, Pt3d & a_newpt, const double a_tol)
Finds the closest point to another point on a segment.
Parameters
[in] a_pt1 First point of segment
[in] a_pt2 Second point of segment
[in] a_pt Point used to find closest point on the segment
[out] a_newpt The point on the segment (a_pt1, a_pt2) that is closest to a_pt.
[in] a_tol Tolerance
Returns
parametric value along the line a_pt1, a_pt2 that is the location of a_newpt.
Definition at line 1649 of file geoms.cpp.
References xms::gmFindClosestPtOnSegment(), and xms::gmPtDistanceAlongSegment().
Referenced by xms::gmFindClosestPtOnSegment().
gmInsideOfLineWithTol()
bool xms::gmInsideOfLineWithTol (const Pt3d & a_vertex1, const Pt3d & a_vertex2, const Pt3d & a_oppositevertex, const double a_x, const double a_y, const double a_tol)
Returns TRUE if the Point on the same side of the line (defined by vertex1 and vertex2) as oppositevertex.
Parameters
[in] a_vertex1 : First point on the line segment
[in] a_vertex2 : Second point on the line segment
[in] a_oppositevertex : Point on one side of the line
[in] a_x : X location of the point being tested
[in] a_y : Y location of the point being tested
[in] a_tol : Tolerance for degenerate cases
Returns
true if the a_x, a_y are inside the line defined by a_vertex1 and a_vertex2. Inside is defined as the opposite side of a_oppositevertex
Definition at line 1717 of file geoms.cpp.
References xms::gmEqualPointsXY(), xms::gmInsideOfLineWithTol(), and sqr().
Referenced by xms::gmInsideOfLineWithTol().
gmInsideOrOnLineWithTol()
bool xms::gmInsideOrOnLineWithTol (const Pt3d * p1, const Pt3d * p2, const Pt3d * inpoint, const double x, const double y, const double tol, double * dist)
Returns true if the (x,y) is on the line segment (p1,p2) or on the same side of the line as "inpoint". ASSERTs in debug if "inpoint" is on the line (within tol).
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] inpoint Point on same side of line as xy if true is returned.
[in] x x of point.
[in] y y of point.
[in] tol Tolerance.
[out] dist How far "outside" the point is. A negative distance indicates point is in by that distance.
Returns
true if in.
Definition at line 1387 of file geoms.cpp.
References xms::gmEqualPointsXY(), xms::gmInsideOrOnLineWithTol(), Mfabs(), and sqr().
Referenced by xms::gmInsideOrOnLineWithTol(), and xms::gmPointInTriangleWithTol().
gmIntersectLineSegmentsWithTol()
bool xms::gmIntersectLineSegmentsWithTol (const Pt3d & one1, const Pt3d & one2, const Pt3d & two1, const Pt3d & two2, double * xi, double * yi, double * zi1, double * zi2, double tol)
Intersects the plan projection of two line segments.
Parameters
one1 first point on segment 1
one2 second point on segment 1
two1 first point on segment 2
two2 second point on segment 2
xi x coord of intersection
yi y coord of intersection
zi1 z coord of intersection on segment 1
zi2 z coord of intersection on segemnt 2
tol tolerance for geometric comparison
segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
Returns
true if lines intersect, else false
Definition at line 406 of file geoms.cpp.
References EQ_TOL(), xms::gmColinearWithTol(), xms::gmEqualPointsXY(), xms::gmIntersectLineSegmentsWithTol(), GT_TOL(), and LT_TOL().
Referenced by xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromEdge(), xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromPoint(), xms::gmIntersectLineSegmentsWithTol(), and xms::TrBreaklineAdderImpl::ProcessSegmentBySwapping().
gmIntersectTriangleAndLineSegment()
int xms::gmIntersectTriangleAndLineSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_t0, const Pt3d & a_t1, const Pt3d & a_t2, Pt3d & a_IntersectPt)
Determine if the line (described by a_pt1 and a_pt2) intersects the triangle (a_t0, a_t1, a_t2).
Parameters
[in] a_pt1 First point defining a segment
[in] a_pt2 Second point defining a segment
[in] a_t0 First point defining a triangle
[in] a_t1 Second point defining a triangle
[in] a_t2 Third point defining a triangle
[out] a_IntersectPt The point of intersection if the segment and triangle intersect
Returns
-1 if triangle is degenerate (a point or a line) 0 if line does not intersect triangle 1 if line does intersect triangle 2 if line and triangle are in the same plane
Definition at line 2010 of file geoms.cpp.
References xms::gmCross3D(), xms::gmDot3D(), xms::gmIntersectTriangleAndLineSegment(), and XM_ZERO_TOL.
Referenced by xms::gmIntersectTriangleAndLineSegment().
gmLinesIntersect()
bool xms::gmLinesIntersect (const Pt3d & one1, const Pt3d & one2, const Pt3d & two1, const Pt3d & two2)
intersects the plan projection of two line segments (bad func name) segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
Parameters
one1 first point on first segment
one2 second point on first segment
two1 first point on second segment
two2 second point on second segment
Returns
true if segments intersect, else false
Definition at line 941 of file geoms.cpp.
References xms::gmLinesIntersect(), GT_TOL(), LT_TOL(), and XM_ZERO_TOL.
Referenced by xms::gmLinesIntersect().
gmMiddleZ()
double xms::gmMiddleZ (const VecPt3d & a_points)
Returns the z value halfway between the max and min z. Different from the average z (where many points can skew the average).
Parameters
a_points vector of locations
Returns
Middle z value.
Definition at line 139 of file geoms.cpp.
References xms::gmMiddleZ().
Referenced by xms::gmMiddleZ().
gmOnLineAndBetweenEndpointsWithTol()
bool xms::gmOnLineAndBetweenEndpointsWithTol (const Pt3d & a_pt1, const Pt3d & a_pt2, const double a_x, const double a_y, double a_tol)
determines if (x,y) is on the line passing through p1 & p2 and between p1 & p2.
Parameters
a_pt1 first location defining segment
a_pt2 second location defining segment
a_x x coord
a_y y coord
a_tol tolerance for comparison
Returns
true if on line segment
Note
For simple test of colinearity, call gmOnLineWithTol or gmColinear
Definition at line 742 of file geoms.cpp.
References xms::gmOnLineAndBetweenEndpointsWithTol(), xms::gmOnLineWithTol(), Mmax(), and Mmin().
Referenced by xms::gmOnLineAndBetweenEndpointsWithTol(), and xms::GmMultiPolyIntersectorImpl::PointsOnSegment().
gmOnLineWithTol()
bool xms::gmOnLineWithTol (const Pt3d & p1, const Pt3d & p2, const double x, const double y, const double tol)
Determines if a point (x,y) is on the line defined by p1 and p2. Assumes p1 and p2 aren't the same.
Parameters
p1 first location defining a line
p2 second location defining a line
x x coord of point to test
y y coord of point to test
tol tolerance for geometric comparison
Returns
Returns true if the Point is on the line passing through p1 and p2 within the tolerance passed. note: you should always be careful to consider the case when p1 and p2 are very close to each other but not to x,y. in that case this test will almost always fail because it will be more susceptible to roundoff error. if you need to know if three points are colinear you should use the gmColinear function.
Definition at line 707 of file geoms.cpp.
References xms::gmEqualPointsXY(), xms::gmOnLineWithTol(), and sqr().
Referenced by xms::gmColinearWithTol(), xms::gmOnLineAndBetweenEndpointsWithTol(), and xms::gmOnLineWithTol().
gmOrderPointsCounterclockwise() [1/2]
void xms::gmOrderPointsCounterclockwise (const VecPt3d & a_pts, VecInt & a_ccwOrder, int a_startindex)
Orders array of points counter clockwise. Given non-empty array of points. array of point indices ordered counter clockwise based on the angle from the centroid where angle starts at point at startindex.
Parameters
[in] a_pts Array of points
[out] a_ccwOrder Array of indices to points
[in] a_startindex Starting position in arrays
Definition at line 1570 of file geoms.cpp.
References xms::gmOrderPointsCounterclockwise().
Referenced by xms::gmOrderPointsCounterclockwise().
gmOrderPointsCounterclockwise() [2/2]
void xms::gmOrderPointsCounterclockwise (VecPt3d & a_pts)
Overload to gmOrderPointsCounterclockwise.
Parameters
[out] a_pts Array of points
Definition at line 1625 of file geoms.cpp.
References xms::gmOrderPointsCounterclockwise().
gmPerpendicularAngle()
double xms::gmPerpendicularAngle (const Pt3d & a_pt1, const Pt3d & a_pt2)
Returns the angle in radians perpendicular to the two points.
Parameters
[in] a_pt1 The first point defining an edge
[in] a_pt2 The second point defining an edge
Returns
angle perpendicular to the edge
Definition at line 1809 of file geoms.cpp.
References xms::gmPerpendicularAngle(), sqr(), and XM_PI.
Referenced by xms::gmPerpendicularAngle().
gmPointInOrOnBox2d()
bool xms::gmPointInOrOnBox2d (const Pt3d & a_bMin, const Pt3d & a_bMax, const Pt3d & a_pt)
finds if a point is in or on a box in 2d
Parameters
[in] a_bMin Min x,y of first box
[in] a_bMax Max x,y of first box
[in] a_pt point being tested
Returns
true if the point is in or on a box
Definition at line 51 of file geoms.cpp.
References xms::gmPointInOrOnBox2d().
Referenced by xms::gmPointInOrOnBox2d().
gmPointInPolygon2D() [1/7]
template<typename T > int xms::gmPointInPolygon2D (const T * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
Determines whether (a_x, a_y) is inside=1, on=0, or outside=-1 the polygon defined by the given vertices.
DON'T repeat the first point at the end of the polygon array
See also
EFastPointInPoly
GmPolygon
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 994 of file geoms.cpp.
References xms::gmPointInPolygon2D().
Referenced by xms::gmPointInPolygon2D().
gmPointInPolygon2D() [2/7]
int xms::gmPointInPolygon2D (const Pt3d * a_verts, size_t a_num, double a_x, double a_y)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1092 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D() [3/7]
int xms::gmPointInPolygon2D (const Pt3d * a_verts, size_t a_num, Pt3d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1103 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D() [4/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt2d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1114 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D() [5/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt3d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1125 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D() [6/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt2i a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1136 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D() [7/7]
int xms::gmPointInPolygon2D (const VecPt3d & a_verts, const Pt3d & a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1146 of file geoms.cpp.
References xms::gmPointInPolygon2D(), and xms::gmXyTol().
gmPointInPolygon2D< Pt2d >()
template int xms::gmPointInPolygon2D< Pt2d > (const Pt2d * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInPolygon2D< Pt2i >()
template int xms::gmPointInPolygon2D< Pt2i > (const Pt2i * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInPolygon2D< Pt3d >()
template int xms::gmPointInPolygon2D< Pt3d > (const Pt3d * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInTriangleWithTol()
bool xms::gmPointInTriangleWithTol (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, double x, double y, double tol)
Returns true if (x,y) is in the tri formed by p1, p2, p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
[in] x x of point.
[in] y y of point.
[in] tol Tolerance.
Returns
true if in.
Definition at line 1360 of file geoms.cpp.
References xms::gmInsideOrOnLineWithTol(), and xms::gmPointInTriangleWithTol().
Referenced by xms::gmPointInTriangleWithTol().
gmPolygonArea()
double xms::gmPolygonArea (const Pt3d * pts, size_t npoints)
Compute 2d planview projection of area of polygon.
Parameters
pts locations defining the polygon
npoints number of pts
Returns
Area of the polygon.
CCW = positive area, CW = negative. Don't repeat the last point.
Definition at line 1474 of file geoms.cpp.
References xms::gmPolygonArea().
Referenced by xms::gmPolygonArea().
gmPtDistanceAlongSegment()
double xms::gmPtDistanceAlongSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt, const double a_tol)
Finds the distance along a segment for the location closest to a_pt.
Parameters
[in] a_pt1 First point of segment
[in] a_pt2 Second point of segment
[in] a_pt Point used to find closest point on the segment
[in] a_tol Tolerance
Returns
parametric value along the line a_pt1, a_pt2 that is the closest location to a_pt.
Definition at line 1684 of file geoms.cpp.
References xms::gmPtDistanceAlongSegment().
Referenced by xms::AnisotropicInterpolator::GetParameterInSegment(), xms::gmFindClosestPtOnSegment(), and xms::gmPtDistanceAlongSegment().
gmPtInCircumcircle()
PtInOutOrOn_enum xms::gmPtInCircumcircle (const Pt3d & pt, Pt3d circumcirclePts[3])
Is a given point inside a circumcircle defined by three points?
Parameters
pt The point.
circumcirclePts 3 points on the circumcircle.
Returns
PtInOutOrOn_enum
Definition at line 158 of file geoms.cpp.
References xms::gmCircumcircleWithTol(), xms::gmPtInCircumcircle(), xms::gmXyTol(), xms::PT_ERROR, xms::PT_IN, xms::PT_ON, xms::PT_OUT, and sqr().
Referenced by xms::gmPtInCircumcircle(), and xms::TrTinImpl::PointIsInCircumcircle().
gmTurn()
Turn_enum xms::gmTurn (const Pt3d & a_v1, const Pt3d & a_v2, const Pt3d & a_v3, double a_angtol)
Determine if angle a_v1, a_v2, a_v3 is a left turn, a right turn, colinear 180 degrees, or colinear 0 degrees.
Parameters
a_v1 first of 3 locations defining an angle
a_v2 second of 3 locations defining an angle
a_v3 third of 3 locations defining an angle
a_angtol tolerance for comparing angle see notes
Returns
the type of turn defined by the angle
Note
a_angtol was added in August 2014 by AKZ (with consultation by APC). This is the sine of the angle that is considered a turn at all. The default is 0.0017453 (sine 0.1 and sine 179.9). Therefore, this function will only classify two segments as colinear if the angle between edges is less than this tol of the angle between edges is greater than 180-tol. In that case it will determine if the angle is considered to be 180 TURN_COLINEAR_180 or 0 TURN_COLINEAR_0 based on the cosine.
Definition at line 838 of file geoms.cpp.
References xms::gmTurn(), xms::TURN_COLINEAR_0, xms::TURN_COLINEAR_180, xms::TURN_LEFT, and xms::TURN_RIGHT.
Referenced by xms::gmTurn(), and xms::GmMultiPolyIntersectionSorterTerse::RemoveDuplicateEdges().
gmXyDistance() [1/2]
double xms::gmXyDistance (double x1, double y1, double x2, double y2)
Compute the 2d distance between 2 points.
Parameters
x1 x coord of location 1
y1 y coord of location 1
x2 x coord of location 2
y2 y coord of location 2
Returns
Distance between location 1 and 2
Note
See gmActualDistance if you don't want the distance in model units.
Definition at line 807 of file geoms.cpp.
References xms::gmXyDistance(), and sqr().
Referenced by xms::GmMultiPolyIntersectorImpl::CalculateBuffer(), xms::TrTinImpl::CheckTriangle(), xms::GmMultiPolyIntersectorImpl::ComputeTValues(), xms::InterpNatNeighImpl::FillCenterVec(), xms::gmComputeXyTol(), and xms::gmXyDistance().
gmXyDistance() [2/2]
double xms::gmXyDistance (const Pt3d & pt1, const Pt3d & pt2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] pt1 Point 1.
[in] pt2 Point 2.
Returns
Distance.
Definition at line 817 of file geoms.cpp.
References xms::gmXyDistance(), and sqr().
gmXyDistanceSquared()
double xms::gmXyDistanceSquared (const Pt3d & pt1, const Pt3d & pt2)
Calculate XY distance between two 3D points.
Parameters
[in] pt1 First point.
[in] pt2 Second point.
Returns
distance squared.
Definition at line 188 of file geoms.cpp.
References xms::gmXyDistanceSquared(), and sqr().
Referenced by xms::InterpNatNeighImpl::GetNatNeighTriangles(), xms::gmXyDistanceSquared(), and xms::InterpNatNeighImpl::PtInTriCircumCircle().
gmXyTol()
double xms::gmXyTol (bool a_set, double a_value)
Get or set (set first time) global xy tolerance for float operations.
Parameters
a_set True if setting.
a_value The value if setting.
Returns
XY tolerance.
Definition at line 1216 of file geoms.cpp.
References xms::gmXyTol().
Referenced by xms::gmEqualPointsXY(), xms::gmEqualPointsXYZ(), xms::gmPointInPolygon2D(), xms::gmPtInCircumcircle(), xms::gmXyTol(), and xms::InterpIdwImpl::InterpWeights().
gmZTol()
double xms::gmZTol (bool a_set, double a_value)
Get or set (set first time) global z tolerance for float operations.
Parameters
a_set True if setting.
a_value The value if setting.
Returns
Z tolerance.
Definition at line 1229 of file geoms.cpp.
References xms::gmZTol().
Referenced by xms::gmZTol().