xmsinterp: /home/conan/xmsinterp/matrices/matrix.cpp File Reference
matrix.cpp File Reference
routines for manipulating matrices
#include <xmsinterp/matrices/matrix.h>
#include <cmath>
#include <xmscore/points/pt.h>
#include <xmscore/misc/XmLog.h>
#include <xmscore/misc/xmstype.h>
Functions
int xms::mxLUDecomp (double **mat, int n, int *indx, double *d)
Decompose an n x n matrix into Upper & Lower trianglar (in place), from "Numerical Recipes in C" p 43.
int xms::mxLUBcksub (double **mat, int n, const int *indx, double *b)
solve [mat]{x} = {b} by back substitution (mat = LU of mat), from "Numerical Recipes in C" p 44.
bool xms::mxiLudcmp3 (double mat[3][3], int indx[3], double *d)
Decomposes a 3 x 3 matrix into Upper & Lower trianglar(in place)
void xms::mxiLubksb3 (const double mat[3][3], const int indx[3], double b[3])
solve [mat]{x} = {b} by back substitution (mat = LU of mat)
bool xms::mxSolveNxN (double **A, double *x, double *b, int n)
Solves the matrix equation [A]*{x}={b} for {x} where [A] is NxN and {x} and {b} are Nx1 vectors. The matrix A is replaced with the LU decomposition of A.
bool xms::mxSolveBandedEquations (double **a, double *x, double *b, int numeqs, int halfbandwidth)
Solves the matrix equation [a][x]=[b] using gauss elimination.
bool xms::mxSolve3x3 (double A[3][3], double x[3], double b[3])
Solves the matrix equation [A]*{x}={b} for {x} where [A] is 3x3 and {x} and {b} are 3x1 vectors.
int xms::mxInvert4x4 (const double matrix[4][4], double inv[4][4])
Compute the inverse of a transformation matrix. Checks for special case of Orthogonal 4x4 and does easy inverse otherwise uses Gauss-Jordan Elimination with full pivoting and scaling with partial unraveling of loops for speed. See Numerical Recipes in C pages 36-37.
void xms::mxPointMult (Pt3d *pt, const double ctm[4][4])
Multiplies a point by a transformation matrix.
void xms::mxCopy4x4 (double copy[4][4], const double matrix[4][4])
Copy a transformation matrix. Simply uses memcpy.
void xms::mxIdent4x4 (double matrix[4][4])
Sets a transformation matrix to identity.
void xms::mxMult4x4 (double product[4][4], const double matrix1[4][4], const double matrix2[4][4])
Multiplies two transformation matrices.
void xms::mxRotate4x4 (double xrot, double yrot, double zrot, double rMatt[4][4])
return a rotation matrix with specified x, y, z rotations z - y - x order
void xms::mxTranslate4x4 (const Pt3d &a_translation, double a_mx[4][4])
return a translation matrix with specified translation z - y - x order
Detailed Description
routines for manipulating matrices
The routines in this file come from "Numerical Recipes in C" by Press et al. important: to use these routines properly, the matrices and vectors should be declared as pointers and initialized from [1..n] using the routines defined in this file.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file matrix.cpp.
Function Documentation
mxCopy4x4()
void xms::mxCopy4x4 (double copy[4][4], const double matrix[4][4])
Copy a transformation matrix. Simply uses memcpy.
Parameters
copy matrix that will have result of copy
matrix 4x4 matrix to copy
Definition at line 563 of file matrix.cpp.
References xms::mxCopy4x4().
Referenced by xms::mxCopy4x4(), xms::mxInvert4x4(), and xms::mxMult4x4().
mxIdent4x4()
void xms::mxIdent4x4 (double matrix[4][4])
Sets a transformation matrix to identity.
Parameters
matrix matrix to change
Definition at line 571 of file matrix.cpp.
References xms::mxIdent4x4().
Referenced by xms::mxIdent4x4(), xms::mxRotate4x4(), and xms::mxTranslate4x4().
mxiLubksb3()
void xms::mxiLubksb3 (const double mat[3][3], const int indx[3], double b[3])
solve [mat]{x} = {b} by back substitution (mat = LU of mat)
Parameters
mat matrix[3][3]
indx
b vector of solution [mat]{x} = {b}
Definition at line 231 of file matrix.cpp.
References xms::mxiLubksb3().
Referenced by xms::mxiLubksb3(), and xms::mxSolve3x3().
mxiLudcmp3()
bool xms::mxiLudcmp3 (double mat[3][3], int indx[3], double * d)
Decomposes a 3 x 3 matrix into Upper & Lower trianglar(in place)
Parameters
mat matrix[3][3]
indx
d determinant of matrix
Returns
false if errors are encountered else true
Definition at line 157 of file matrix.cpp.
References xmlog::debug, xms::mxiLudcmp3(), and XM_LOG.
Referenced by xms::mxiLudcmp3(), and xms::mxSolve3x3().
mxInvert4x4()
int xms::mxInvert4x4 (const double matrix[4][4], double inv[4][4])
Compute the inverse of a transformation matrix. Checks for special case of Orthogonal 4x4 and does easy inverse otherwise uses Gauss-Jordan Elimination with full pivoting and scaling with partial unraveling of loops for speed. See Numerical Recipes in C pages 36-37.
Parameters
matrix matrix[4][4] to invert
inv inverse of matrix
Returns
XM_FAILURE if errors are encountered else XM_SUCCESS
Definition at line 422 of file matrix.cpp.
References xmlog::error, xms::mxCopy4x4(), xms::mxInvert4x4(), XM_FAILURE, XM_LOG, and XM_SUCCESS.
Referenced by xms::mxInvert4x4().
mxLUBcksub()
int xms::mxLUBcksub (double ** mat, int n, const int * indx, double * b)
solve [mat]{x} = {b} by back substitution (mat = LU of mat), from "Numerical Recipes in C" p 44.
Parameters
mat matrix[n][n]
n dimension of matrix mat
indx
b vector of solution [mat]{x} = {b}
Returns
XM_SUCCESS
Definition at line 122 of file matrix.cpp.
References xms::mxLUBcksub(), and XM_SUCCESS.
Referenced by xms::mxLUBcksub(), and xms::mxSolveNxN().
mxLUDecomp()
int xms::mxLUDecomp (double ** mat, int n, int * indx, double * d)
Decompose an n x n matrix into Upper & Lower trianglar (in place), from "Numerical Recipes in C" p 43.
Parameters
mat matrix[n][n]
n dimension of matrix mat
indx
d matrix determinant
Returns
XM_FAILURE if errors encountered else XM_SUCCESS
Definition at line 47 of file matrix.cpp.
References xms::mxLUDecomp(), XM_FAILURE, and XM_SUCCESS.
Referenced by xms::mxLUDecomp(), and xms::mxSolveNxN().
mxMult4x4()
void xms::mxMult4x4 (double product[4][4], const double matrix1[4][4], const double matrix2[4][4])
Multiplies two transformation matrices.
Parameters
product result of matrix1*matrix2
matrix1 [4][4] matrix multiplied by matrix2
matrix2 [4][4] matrix multiplied by matrix1
Definition at line 585 of file matrix.cpp.
References xms::mxCopy4x4(), and xms::mxMult4x4().
Referenced by xms::mxMult4x4().
mxPointMult()
void xms::mxPointMult (Pt3d * pt, const double ctm[4][4])
Multiplies a point by a transformation matrix.
Parameters
pt point to multiply
ctm transform matrix[4][4].
Definition at line 549 of file matrix.cpp.
References xms::mxPointMult().
Referenced by xms::mxPointMult().
mxRotate4x4()
void xms::mxRotate4x4 (double xrot, double yrot, double zrot, double rMatt[4][4])
return a rotation matrix with specified x, y, z rotations z - y - x order
Parameters
xrot x rotation amount
yrot y rotation amount
zrot z rotation amount
rMatt matrix to be built
Definition at line 611 of file matrix.cpp.
References xms::mxIdent4x4(), xms::mxRotate4x4(), and XM_PI.
Referenced by xms::mxRotate4x4().
mxSolve3x3()
bool xms::mxSolve3x3 (double A[3][3], double x[3], double b[3])
Solves the matrix equation [A]*{x}={b} for {x} where [A] is 3x3 and {x} and {b} are 3x1 vectors.
Parameters
A matrix[3][3]
x vector[3]
b vector[3] of solution [A]{x} = {b}
Returns
XM_FAILURE if errors are encountered else XM_SUCCESS
Definition at line 399 of file matrix.cpp.
References xms::mxiLubksb3(), xms::mxiLudcmp3(), and xms::mxSolve3x3().
Referenced by xms::NodalFuncImpl::ComputeGradientForPoint(), and xms::mxSolve3x3().
mxSolveBandedEquations()
bool xms::mxSolveBandedEquations (double ** a, double * x, double * b, int numeqs, int halfbandwidth)
Solves the matrix equation [a][x]=[b] using gauss elimination.
Parameters
a matrix[n][n]
x vector nx1
b vector of solution [A]{x} = {b}
numeqs number of equations
halfbandwidth
Note
Assumes that [a] is a banded symmetric matrix with only the upper half stored. If a matrix is banded and symmetric, only values at or above the main diagonal need to be stored. When setting up the matrix, the indices in the equivalent full matrix are mapped to the indices in the banded matrix with the following formula (i,j)=(i,j-i+1) where j is the row number and i is the column number.
Returns
false if errors encountered else true
Definition at line 325 of file matrix.cpp.
References xms::mxSolveBandedEquations().
Referenced by xms::mxSolveBandedEquations(), xms::NodalFuncImpl::NodalFunc2d(), and xms::NodalFuncImpl::NodalFunc3d().
mxSolveNxN()
bool xms::mxSolveNxN (double ** A, double * x, double * b, int n)
Solves the matrix equation [A]*{x}={b} for {x} where [A] is NxN and {x} and {b} are Nx1 vectors. The matrix A is replaced with the LU decomposition of A.
Parameters
A matrix[n][n]
x vector nx1
b vector of solution [A]{x} = {b}
n size of matrix A
Returns
false if errors encountered else true
Definition at line 268 of file matrix.cpp.
References xms::mxLUBcksub(), xms::mxLUDecomp(), xms::mxSolveNxN(), and XM_FAILURE.
Referenced by xms::NodalFuncImpl::ComputeGradientForPoint(), and xms::mxSolveNxN().
mxTranslate4x4()
void xms::mxTranslate4x4 (const Pt3d & a_translation, double a_mx[4][4])
return a translation matrix with specified translation z - y - x order
Parameters
a_translation translation distances in x, y, and z.
a_mx matrix to be built
Definition at line 638 of file matrix.cpp.
References xms::mxIdent4x4(), and xms::mxTranslate4x4().
Referenced by xms::mxTranslate4x4().