xmsinterp: /home/conan/xmsinterp/triangulate/triangles.cpp File Reference
triangles.cpp File Reference
Functions dealing with triangles.
#include <xmsinterp/geometry/geoms.h>
#include <xmscore/stl/vector.h>
#include <xmsinterp/triangulate/triangles.h>
Functions
double xms::trArea (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt3)
Return the signed planar area of the triangle (CCW Positive).
void xms::trBuildGridTrianglePolys (int rows, int cols, VecPt3d &a_points, VecInt2d &a_polys)
Create something like this:
void xms::trBuildGridPolys (int rows, int cols, VecPt3d &pts, VecInt2d &polys)
Build something like this:
Detailed Description
Functions dealing with triangles.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file triangles.cpp.
Function Documentation
trArea()
double xms::trArea (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt3)
Return the signed planar area of the triangle (CCW Positive).
This uses the formula: (-x2*y1 + x3*y1 + x1*y2 - x3*y2 - x1*y3 + x2*y3) / 2 reworked to ensure precision is not lost with large numbers by moving the triangle to the origin by subtracting the first vertex's location from all vertices.
Parameters
[in] a_pt1 First point on triangle.
[in] a_pt2 Second point on triangle.
[in] a_pt3 Third point on triangle.
Returns
The area.
Definition at line 46 of file triangles.cpp.
References xms::trArea().
Referenced by xms::gmCounterClockwiseTri(), xms::TrTriangulatorPoints::ReceiveTriangle(), xms::TrTinImpl::SwapEdge(), xms::trArea(), and xms::TrTinImpl::TriangleArea().
trBuildGridPolys()
void xms::trBuildGridPolys (int rows, int cols, VecPt3d & pts, VecInt2d & polys)
Build something like this:
///  (0, 0)
///    0-------------1-------------2
///    |             |             |
///    |             |             |
///    |      1      |      2      |
///    |             |             |
///    |             |             |
///    3-------------4-------------5
///                             (20,-10)
///
Parameters
[in] rows Number of rows
[in] cols Number of columns
[out] pts The points.
[out] polys The polygons.
Definition at line 132 of file triangles.cpp.
References xms::trBuildGridPolys().
Referenced by xms::trBuildGridPolys(), and xms::trBuildGridTrianglePolys().
trBuildGridTrianglePolys()
void xms::trBuildGridTrianglePolys (int rows, int cols, VecPt3d & a_points, VecInt2d & a_polys)
Create something like this:
/// (0, 0)
///    0-------------1-------------2
///    |\     4     /|\     8     /|
///    |  \       /  |  \       /  |
///    |    \   /    |    \   /    |
///    |  1   3    3 |  5   4    7 |
///    |    /   \    |    /   \    |
///    |  /       \  |  /       \  |
///    |/     2     \|/     6     \|
///    5-------------6-------------7 2
///                            (20, -10)
///
Parameters
[in] rows Number of rows
[in] cols Number of columns
[out] a_points The points.
[out] a_polys The polygons.
Definition at line 72 of file triangles.cpp.
References xms::gmComputeCentroid(), xms::trBuildGridPolys(), and xms::trBuildGridTrianglePolys().
Referenced by GmMultiPolyIntersectorUnitTests::testAlongEdgesInsideToInside(), GmMultiPolyIntersectorUnitTests::testAlongEdgesOutsideToOutside(), GmMultiPolyIntersectorUnitTests::testEdgeThroughOppositeVertexAtAngle(), GmMultiPolyIntersectorUnitTests::testEndAtEdgeFromAdjacent(), GmMultiPolyIntersectorUnitTests::testInsideToEdgeThenThroughAdjacent(), GmMultiPolyIntersectorUnitTests::testInsideToInside(), GmMultiPolyIntersector2IntermediateTests::testLargeNumPolys(), GmMultiPolyIntersector2IntermediateTests::testLargeNumPolysAndSegments(), GmMultiPolyIntersectorUnitTests::testOutsideToOutside(), GmMultiPolyIntersectorUnitTests::testStartAtEdgeThroughAdjacent(), GmMultiPolyIntersectorUnitTests::testTouchesEdge(), GmMultiPolyIntersectorUnitTests::testTouchesVertex(), and xms::trBuildGridTrianglePolys().