xmsinterp: /home/conan/xmsinterp/triangulate/detail/triangulate.h File Reference
triangulate.h File Reference
Code that creates a Delauney triangulation from points.
Functions
bool xms::trTriangulateIt (TrTriangulator &a_Client)
Do delaunay divide-and-conquer triangulation.
Detailed Description
Code that creates a Delauney triangulation from points.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file triangulate.h.
Function Documentation
trTriangulateIt()
bool xms::trTriangulateIt (TrTriangulator & a_Client)
Do delaunay divide-and-conquer triangulation.
This algorithm can leave triangles that are VERY long and thin. The default ratio should be sufficient to get rid of these (on the exterior only). If you want to supply a bigger ratio to get rid of more triangles, you can, or you can do it on your own after you call this function.
Parameters
[in,out] a_Client Class used to help do the triangulation.
Returns
true if no errors.
Definition at line 2656 of file triangulate.cpp.
References xmlog::error, xms::trTriangulateIt(), and XM_LOG.
Referenced by TrTriangulatorPointsUnitTests::test1(), xms::TrTriangulator::Triangulate(), and xms::trTriangulateIt().